const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('ethers'),C=require('../src/circuits.js'),P=require('../src/provenance.js');
const publisher=new E.Wallet('0x'+'1'.repeat(64)),other=new E.Wallet('0x'+'2'.repeat(64));
const CPU='0x'+'3'.repeat(40),HASH='0x'+'a'.repeat(64),BLOCK='0x'+'b'.repeat(64);
function fixture(){const blueprint=C.PRESETS[0].b,c=C.compile(blueprint);return P.make({chainId:196,processor:CPU,circuitId:'42',txHash:HASH,logIndex:7,blockNumber:123456,blockHash:BLOCK,publisher:publisher.address,netlist:c.netlist,nIn:c.nIn,nOut:c.nOut,nState:c.nState,kind:c.kind},{blueprint,parent:'oathkeeper',parentNetlistHash:E.keccak256(c.netlist)});}
function changed(pkg,fn){const copy=JSON.parse(JSON.stringify(pkg));fn(copy);return copy;}
test('Publication proof binds immutable circuit, event, ABI, blueprint and exact parent version',()=>{const p=fixture(),raw=P.exportPackage(p),loaded=P.parse(raw);assert.deepEqual(loaded,p);assert.equal(loaded.proof.publisher,publisher.address);assert.equal(loaded.proof.netlistHash,E.keccak256(C.compile(C.PRESETS[0].b).netlist));for(const [name,mutate] of [['publisher',x=>x.proof.publisher=other.address],['processor',x=>x.proof.processor=other.address],['circuit',x=>x.proof.circuitId='43'],['block',x=>x.proof.blockHash='0x'+'c'.repeat(64)],['netlist',x=>x.proof.netlist='0x00'],['abi',x=>x.proof.abi.nOut=22],['blueprint',x=>x.work.blueprint.name='changed'],['parent',x=>x.work.parent.netlistHash='0x'+'c'.repeat(64)]]){const bogus=changed(p,mutate);if(['publisher','processor','circuit','block','parent'].includes(name)){assert.notDeepEqual(P.validate(bogus),p,name);}else assert.throws(()=>P.validate(bogus),undefined,name);}});
test('Authorship is a separately signed self-declaration and tampering any signed identity/version fails',async()=>{const p=fixture(),claim={signer:publisher.address,role:'author',royaltyRecipient:other.address,note:'Created with a collaborator'},signature=await publisher.signMessage(P.statement(p,claim)),signed=P.addClaim(p,claim,signature);assert.equal(P.validate(signed).claims[0].signer,publisher.address);assert.equal(signed.proof.publisher,publisher.address);assert.throws(()=>P.addClaim(signed,claim,signature),/CLAIM_EXISTS/);for(const mutate of [x=>x.claims[0].signer=other.address,x=>x.claims[0].role='publisher',x=>x.claims[0].royaltyRecipient=publisher.address,x=>x.claims[0].signature='0x'+'0'.repeat(130),x=>x.proof.publisher=other.address,x=>x.proof.blockNumber=123457,x=>x.proof.logIndex=8,x=>x.proof.blockHash='0x'+'c'.repeat(64),x=>x.proof.circuitId='43',x=>x.work.parent.netlistHash='0x'+'c'.repeat(64)])assert.throws(()=>P.validate(changed(signed,mutate)));const unsigned=fixture();assert.equal(P.validate(unsigned).claims.length,0);});
test('Coauthors can sign separately; a signature from one cannot impersonate another',async()=>{let p=fixture();for(const [wallet,role]of [[publisher,'author'],[other,'coauthor']]){const claim={signer:wallet.address,role,royaltyRecipient:null,note:''};p=P.addClaim(p,claim,await wallet.signMessage(P.statement(p,claim)));}assert.deepEqual(P.validate(p).claims.map(c=>c.role),['author','coauthor']);const lie={signer:other.address,role:'publisher',royaltyRecipient:null,note:''};await assert.rejects(async()=>P.addClaim(p,lie,await publisher.signMessage(P.statement(p,lie))),/INVALID_AUTHOR_SIGNATURE/);});
test('Certificate store survives 30-transaction journal pruning and roundtrips across browsers',async()=>{const memory=()=>{const data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),data};},a=memory(),b=memory();let p=fixture();const claim={signer:publisher.address,role:'author',royaltyRecipient:null,note:''};p=P.addClaim(p,claim,await publisher.signMessage(P.statement(p,claim)));P.save(a,p);a.setItem('nr.oath.transactions','[]');assert.equal(P.list(a).length,1);const exportText=P.exportPackage(P.list(a)[0]);P.save(b,P.parse(exportText));assert.deepEqual(P.list(b),[p]);assert.equal(P.list(a)[0].claims[0].signer,publisher.address);});
test('Rebuilding an old proof preserves signed claims and merges independent coauthors',async()=>{const data=new Map(),store={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},base=fixture(),a={signer:publisher.address,role:'author',royaltyRecipient:null,note:''},b={signer:other.address,role:'coauthor',royaltyRecipient:null,note:''};const first=P.addClaim(base,a,await publisher.signMessage(P.statement(base,a))),second=P.addClaim(base,b,await other.signMessage(P.statement(base,b)));P.save(store,first);assert.equal(P.save(store,base).claims.length,1);assert.equal(P.save(store,second).claims.length,2);assert.equal(P.list(store)[0].claims.length,2);assert.throws(()=>P.save(store,changed(base,x=>x.proof.txHash='0x'+'c'.repeat(64))),/PROVENANCE_CONFLICT/);const revised=P.addClaim(base,{...a,note:'revised'},await publisher.signMessage(P.statement(base,{...a,note:'revised'})));assert.throws(()=>P.save(store,revised),/AUTHOR_CLAIM_CONFLICT/);assert.equal(P.list(store)[0].claims.length,2);});
