const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('ethers'),X=require('../src/xlayer.js'),C=require('../src/circuits.js');
const SIGNER=new E.Wallet('0x'+'1'.repeat(64)),CPU='0x'+'2'.repeat(40),MAT='0x'+'3'.repeat(40),ACCOUNT=SIGNER.address,OTHER='0x'+'5'.repeat(40);
function fixture(){
 const c=C.compile(C.PRESETS[0].b),fi=new E.Interface(X.FABI),ci=new E.Interface(X.CABI),ti=new E.Interface(X.TABI),state={chain:196,registered:true,back:CPU,price:10000000000n,protocol:660000000000000n,fee:1300000000000000n,supply:100000n,minted:0n,balances:[0n,0n],sent:[],receipts:new Map(),mismatch:false,meta:false};
 const invoke=async(tx)=>{
  const iface=tx.to.toLowerCase()===X.FACTORY?fi:tx.to.toLowerCase()===CPU?ci:ti,p=iface.parseTransaction({data:tx.data});let out;
  switch(p.name){case'isCPU':out=[state.registered];break;case'deployFee':out=[6600000000000000n];break;case'transistors':out=[MAT];break;case'circuits':out=[state.back];break;case'supplyCap':out=[state.supply];break;case'minted':out=[state.minted];break;case'mintPrice':out=[state.price];break;case'protocolFee':out=[state.protocol];break;case'TAPEOUT_FEE':out=[state.fee];break;case'balanceOf':out=[state.balances[Number(p.args[1])]];break;case'netlist':out=[c.netlist];break;case'ownerOf':out=[ACCOUNT];break;case'circuitInfo':out=[c.nIn,c.nOut,c.nState,c.nodes.length+(state.meta?1:0)];break;case'step':{const unpack=(hex,n)=>Array.from({length:n},(_,i)=>(E.getBytes(hex)[i>>3]>>(i%8))&1),r=C.step(c,unpack(p.args[1],c.nState),unpack(p.args[2],c.nIn));out=[X.pack(r.state),state.mismatch?'0x00':X.pack(r.outputs)];break;}default:throw Error(p.name);}
  return iface.encodeFunctionResult(p.name,out);
 };
 const provider={send:async(method)=>{if(method==='eth_chainId')return E.toQuantity(state.chain);throw Error(method);},getBlockNumber:async()=>123,call:invoke,getTransactionReceipt:async hash=>state.receipts.get(hash)||null};
 const ethereum={request:async({method,params})=>{
  if(method==='eth_chainId')return E.toQuantity(state.chain);if(method==='eth_accounts'||method==='eth_requestAccounts')return[ACCOUNT];if(method==='wallet_switchEthereumChain'){state.chain=196;return null;}if(method==='eth_call')return invoke(params[0]);if(method==='personal_sign')return SIGNER.signMessage(E.getBytes(params[0]));
  if(method==='eth_sendTransaction'){const tx=params[0],hash='0x'+String(state.sent.length+1).padStart(64,'0');state.sent.push(tx);let logs=[];
   if(tx.to.toLowerCase()===MAT){const p=ti.parseTransaction(tx);state.balances[Number(p.args[0])]+=p.args[1];state.minted+=p.args[1];}
   if(tx.to.toLowerCase()===CPU){const event=ci.encodeEventLog(ci.getEvent('TapedOut'),[1,ACCOUNT,c.nodes.length,c.nState]);logs=[{address:CPU,...event,index:0}];state.balances[0]-=BigInt(c.nNand);state.balances[1]-=BigInt(c.nLatch);}
   if(tx.to.toLowerCase()===X.FACTORY){const event=fi.encodeEventLog(fi.getEvent('CPUCreated'),[CPU,MAT,ACCOUNT,'Oath',10000,0]);logs=[{address:X.FACTORY,...event}];}
   state.receipts.set(hash,{hash,status:1,blockNumber:123,blockHash:'0x'+'a'.repeat(64),logs});return hash;
  }throw Error(method);
 }};
 const storage={getItem:()=>null,setItem:()=>{}},adapter=new X.Adapter({provider,ethereum,storage});return{adapter,state,c};
}
test('Readback checks factory, material provenance, metadata and execution without a wallet',async()=>{const {adapter,state,c}=fixture();const result=await adapter.readCircuit(CPU,'1');assert.equal(result.c.netlist,c.netlist);assert.equal(result.block,123);assert.equal(state.sent.length,0);
 state.registered=false;await assert.rejects(adapter.readCircuit(CPU,'1'),/NOT_FACTORY/);state.registered=true;state.back=OTHER;await assert.rejects(adapter.readCircuit(CPU,'1'),/PROVENANCE/);state.back=CPU;state.meta=true;await assert.rejects(adapter.readCircuit(CPU,'1'),/METADATA/);state.meta=false;state.mismatch=true;await assert.rejects(adapter.readCircuit(CPU,'1'),/EXECUTION/);
});
test('Quote uses final NAND/LATCH count, existing balances and both mint fees',async()=>{const {adapter,state,c}=fixture();const q=await adapter.quote(CPU,c,ACCOUNT);assert.equal(q.need[0],BigInt(c.nNand));assert.equal(q.need[1],1n);assert.equal(q.total,BigInt(c.nodes.length)*state.price+2n*state.protocol+state.fee);state.balances=[BigInt(c.nNand),1n];const owned=await adapter.quote(CPU,c,ACCOUNT);assert.equal(owned.total,state.fee);state.supply=1n;state.balances=[0n,0n];await assert.rejects(adapter.quote(CPU,c,ACCOUNT),/SUPPLY/);});
test('Manufacturing sends precise mint, mint, tapeout then verifies returned bytes',async()=>{const {adapter,state,c}=fixture();await adapter.connect();const q=await adapter.quote(CPU,c,ACCOUNT),result=await adapter.manufacture(q);assert.equal(state.sent.length,3);assert.equal(state.sent[0].to.toLowerCase(),MAT);assert.equal(state.sent[1].to.toLowerCase(),MAT);assert.equal(state.sent[2].to.toLowerCase(),CPU);assert.equal(BigInt(state.sent[2].value),state.fee);assert.equal(result.c.netlist,c.netlist);assert.equal(result.evidence.publisher,ACCOUNT);assert.equal(result.evidence.logIndex,0);assert.equal(result.evidence.txHash,'0x'+String(3).padStart(64,'0'));assert.equal(state.balances[0],0n);assert.equal(adapter.busy,false);});
test('Legacy receipts rebuild immutable publication facts; changed transaction, processor and circuit fail',async()=>{const {adapter,state,c}=fixture();await adapter.connect();const q=await adapter.quote(CPU,c,ACCOUNT),made=await adapter.manufacture(q),hash=made.evidence.txHash;const e=await adapter.receiptEvidence(CPU,'1',hash);assert.equal(e.publisher,ACCOUNT);assert.equal(e.netlistHash,E.keccak256(c.netlist));assert.equal(e.blockHash,'0x'+'a'.repeat(64));await assert.rejects(adapter.receiptEvidence(CPU,'2',hash),/TAPEOUT_EVENT_NOT_FOUND|PROOF_CIRCUIT_MISMATCH/);await assert.rejects(adapter.receiptEvidence(OTHER,'1',hash));await assert.rejects(adapter.receiptEvidence(CPU,'1','0x'+'9'.repeat(64)),/RECEIPT_NOT_FOUND/);state.receipts.get(hash).logs[0].index=undefined;await assert.rejects(adapter.receiptEvidence(CPU,'1',hash),/LOG_INDEX_MISSING/);});
test('A provenance statement can only be signed by the connected author wallet',async()=>{const {adapter,state}=fixture();await adapter.connect();const message='Neon Reliquary authorship declaration v1\n{"test":1}',signature=await adapter.signStatement(message,ACCOUNT);assert.equal(E.verifyMessage(message,signature),ACCOUNT);await assert.rejects(adapter.signStatement(message,OTHER),/AUTHOR_WALLET_REQUIRED/);state.chain=1;await assert.rejects(adapter.signStatement(message,ACCOUNT),/ACCOUNT_OR_CHAIN_CHANGED/);});
test('Price changes, expired quote, wrong network and unresolved previous transaction send nothing',async()=>{const {adapter,state,c}=fixture();await adapter.connect();const q=await adapter.quote(CPU,c,ACCOUNT);state.price*=2n;await assert.rejects(adapter.manufacture(q),/QUOTE_CHANGED/);state.price=q.price;q.quotedAt=Date.now()-121000;await assert.rejects(adapter.manufacture(q),/EXPIRED/);q.quotedAt=Date.now();state.chain=1;await assert.rejects(adapter.manufacture(q),/WRONG_CHAIN/);state.chain=196;adapter.log.push({hash:'0x'+'9'.repeat(64),status:'pending'});await assert.rejects(adapter.manufacture(q),/PENDING_DO_NOT_RESEND/);assert.equal(state.sent.length,0);});
test('Processor creation validates exact supplied public parameters and receipt provenance',async()=>{const {adapter,state}=fixture();await assert.rejects(adapter.deployQuote({name:'x',symbol:'X',story:'',supply:'',price:'0'}),/SUPPLY/);await adapter.connect();const q=await adapter.deployQuote({name:'Oath',symbol:'OATH',story:'test',supply:'10000',price:'0'});const result=await adapter.deploy(q);assert.equal(result.address.toLowerCase(),CPU);assert.equal(state.sent.length,1);assert.equal(BigInt(state.sent[0].value),q.fee);});
