const {simulation,ROOT}=require('./sim_harness.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const results=[];
function test(name,fn){try{results.push({test:name,passed:true,details:fn()});}catch(e){results.push({test:name,passed:false,error:e.message});}}
function fixture(hero=4){const s=simulation();s.start({companion:hero});s.clear();const {P,actor}=s.raw();Object.assign(P,{x:0,y:0,hp:0,downed:true,revive:0});Object.assign(actor,{x:300,y:0,dashTime:0,dashCD:0,nextThink:0});return{s,P,actor};}
function advance(s,seconds){for(let i=0;i<Math.round(seconds*60);i++){s.raw().run.time+=1/60;s.coopTick(1/60);s.coopRescue(1/60);}}
test('Both ordinary knight and cleric approach and revive without invincibility',()=>{const rows=[];for(const hero of [0,4]){const {s,P,actor}=fixture(hero);actor.order={tactic:'rescue',stance:'defensive',autoSkills:true,until:Infinity};advance(s,5);assert(!P.downed);assert(P.hp>0&&P.hp<P.maxhp);assert.equal(P.x,0);assert.equal(P.y,0);rows.push({hero,hp:P.hp,rescues:s.raw().run.coopRescues});}return rows;});
test('Repeated overlapping danger cannot reverse rescue approach',()=>{const {s,actor}=fixture();actor.order={tactic:'rescue',stance:'defensive',autoSkills:false,until:Infinity};const normal=s.steer(actor,0,0,{x:100,y:0,count:40},false),rescue=s.steer(actor,0,0,{x:100,y:0,count:40},true);assert(normal.x>0);assert(rescue.x<0);return{normal,rescue};});
test('No automatic escape dash interrupts revive channel with 3 threats',()=>{const {s,P,actor}=fixture();Object.assign(actor,{x:68,y:0,order:{tactic:'rescue',stance:'defensive',autoSkills:true,until:Infinity}});for(let i=0;i<3;i++)s.warnings.push({type:0,x:45,y:i*3,r:190});s.spawn(0,0,220,0);s.hash();for(let i=0;i<150&&P.downed;i++){advance(s,1/60);assert.equal(actor.dashCD,0);}assert(!P.downed);return{hp:P.hp,dashCD:actor.dashCD};});
test('Arrival brakes an already active dash',()=>{const {s,actor}=fixture();Object.assign(actor,{x:50,y:0,dashTime:.2,dashX:1,dashY:0,order:{tactic:'rescue',stance:'aggressive',autoSkills:false,until:Infinity}});s.coopTick(1/60);assert.equal(actor.dashTime,0);assert(actor.x<50);return{x:actor.x};});
test('Rescue clearing skill faces corridor even when closest enemy is behind',()=>{const {s,actor}=fixture();Object.assign(actor,{skillCD:0,order:{tactic:'rescue',stance:'aggressive',autoSkills:true,until:Infinity}});s.spawn(0,0,350,0);for(let i=0;i<3;i++)s.warnings.push({type:0,x:310,y:i,r:100});s.hash();s.coopTick(1/60);assert(Math.cos(actor.aim)<-.99);assert(actor.skillCD>0);return{aim:actor.aim,cooldown:actor.skillCD};});
test('Manual skill suppression and explicit hold remain respected',()=>{const {s,actor}=fixture();Object.assign(actor,{skillCD:0,order:{tactic:'hold',x:300,y:0,autoSkills:false,until:Infinity}});advance(s,1);assert.equal(actor.skillCD,0);assert.equal(actor.x,300);assert.equal(actor.y,0);});
test('Cleric heals nearby living ally even without an enemy target',()=>{const {s,P,actor}=fixture();Object.assign(P,{hp:30,downed:false});Object.assign(actor,{x:100,skillCD:0,order:{tactic:'guard',autoSkills:true,until:Infinity}});s.coopTick(1/60);assert(P.hp>30);assert(actor.skillCD>0);return{playerHP:P.hp,cooldown:actor.skillCD};});
test('Full simulation pause prevents revive progress',()=>{const {s,P}=fixture();s.pause();const hp=P.hp;for(let i=0;i<180;i++)s.tick(1/60);assert.equal(s.raw().state,'paused');assert.equal(P.hp,hp);assert.equal(P.revive,0);});

fs.mkdirSync(path.join(ROOT,'evidence/rescue-fix'),{recursive:true});
fs.writeFileSync(path.join(ROOT,'evidence/rescue-fix/edge-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));assert(results.every(r=>r.passed),'Rescue edge case failed');
