"""Run in a display-enabled Chromium (Xvfb works). No external AI model is called.
The test query guard is enabled only in an in-memory copy; shipped game is unchanged.
Python dependencies: playwright; Chromium and Xvfb are system packages.
"""
from pathlib import Path
import json, os, subprocess, time
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
results=[]
html=(ROOT/'Neon_Reliquary_v3.html').read_text(encoding='utf8').replace("if(!new URLSearchParams(location.search).has('test'))return;",'')
html=html.replace('<body>','<body><script>window.requestAnimationFrame=()=>1;window.__NR_MANUAL_TEST=true;Math.random=(()=>{let a=82103;return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}})();</script>')
display=None
if not os.environ.get('DISPLAY'):
 display=subprocess.Popen(['Xvfb',':99','-screen','0','1440x900x24'],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 time.sleep(.5)
def run():
 with sync_playwright() as pw:
  browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_BIN','/usr/bin/chromium'),headless=False,env={'DISPLAY':os.environ.get('DISPLAY',':99')},args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
  page=browser.new_page(viewport={'width':1280,'height':720});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  page.set_content(html);page.wait_for_function('!!window.__NR')
  page.evaluate('window.check=(p,m)=>{if(!p)throw new Error(m)};window.call=(n,a={})=>NRCoop.call(n,a)')
  def test(name,js):
   try:
    value=page.evaluate(js);r={'test':name,'passed':True,'details':value}
   except Exception as e:r={'test':name,'passed':False,'error':str(e)}
   results.append(r);print(name, 'PASS' if r['passed'] else 'FAIL',str(r.get('details',r.get('error')))[:500],flush=True)
   (ROOT/'tests/test_results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2),encoding='utf8')
  test('Native WebGL2, valid new geometry','''()=>{__NR.render();const info=__NR.snapshot().renderer;check(info.backend.includes('WebGL2'),'No native WebGL2');const models=[];for(let i=0;i<8;i++){let m=nrBoss(i);check(m.data.every(Number.isFinite),'nonfinite geometry');models.push({boss:i,triangles:m.data.length/33});}check(document.querySelector('#game').getContext('webgl2').getError()===0,'GPU error');return{info,models};}''')
  test('Host permission and reserved seats enforced','''async()=>{const denied=await call('nr_join',{slot:1,name:'Tactician'});check(!denied.ok,'joined without consent');__NR.coop.enable(true);const closed=await call('nr_join',{slot:1,name:'Tactician'});check(!closed.ok,'joined closed seat');return{denied,closed};}''')
  test('Three concurrent joins, no fourth seat','''async()=>{__NR.select();for(let i=1;i<=3;i++)__NR.coop.config(i,'external',[2,4,5][i-1]);const joined=await Promise.all([1,2,3].map(slot=>call('nr_join',{slot,name:'AGENT '+slot})));check(joined.every(x=>x.ok),'join failed');window.auth=joined.map(({agentId,token})=>({agentId,token}));const fourth=await call('nr_join',{slot:4,name:'overflow'}),duplicate=await call('nr_join',{slot:1,name:'duplicate'});check(!fourth.ok&&!duplicate.ok,'seat overflow');return{ids:joined.map(x=>x.agentId),fourth,duplicate};}''')
  test('Read tools do not leak tokens or advance clock','''async()=>{const before=await call('nr_observe');const r=await Promise.all([call('nr_observe'),call('nr_events'),call('nr_roster')]);const text=JSON.stringify(r);check(auth.every(x=>!text.includes(x.token)),'token leaked');const after=await call('nr_observe');check(after.tick===before.tick&&after.time===before.time,'read advanced clock');return{tools:NRCoop.listTools().map(t=>t.name),tick:after.tick};}''')
  test('Four independent units; scaling and projectile owners','''()=>{__NR.start({hero:0,mode:'endless',difficulty:0,invincible:true});__NR.advance(3);const r=__NR.coop.raw();check(r.units.length===4,'wrong party size');check(r.scaling.bossHP===2.95&&r.scaling.density===1.54,'incorrect scale');check(r.owners.length===4,'missing weapon ownership');check(r.units.filter(u=>u.id!=='human').every(u=>u.damage>0),'agents did not damage enemies');check(__NR.verify().length===0,'pool issue');return r;}''')
  test('Commands move only their companion','''async()=>{__NR.coop.clear();__NR.setPlayer({x:0,y:0});const a=auth[0],st=await call('nr_observe');__NR.coop.setAgent(a.agentId,{x:-100,y:0,dashTime:0});__NR.coop.setAgent(auth[1].agentId,{x:-350,y:-300,dashTime:0});__NR.coop.setAgent(auth[2].agentId,{x:350,y:300,dashTime:0});const r=await call('nr_command',{...a,runId:st.runId,seq:1,tactic:'move',x:200,y:0,autoSkills:false});check(r.ok,'order failed '+r.error);const before=__NR.snapshot().position;__NR.advance(.3);const after=__NR.snapshot().position,u=__NR.coop.observe().units.find(u=>u.id===a.agentId);check(u.x>-60,'companion did not move');check(before.x===after.x&&before.y===after.y,'agent moved human');return{human:after,agent:{x:u.x,y:u.y}};}''')
  test('Replay, wrong token, stale run and invalid numbers rejected','''async()=>{const a=auth[0],st=await call('nr_observe'),base={...a,runId:st.runId,seq:2,tactic:'guard'};const cases=[{...base,seq:1},{...base,token:'0'.repeat(32)},{...base,runId:'wrong'},{...base,x:NaN},{...base,y:Infinity},{...base,x:99999},{...base,damage:999},{...base,target:'e99999:3'}];const r=await Promise.all(cases.map(x=>call('nr_command',x)));check(r.every(x=>!x.ok),'bad command accepted');return r;}''')
  test('Skill cooldown cannot be bypassed by repeated calls','''async()=>{const a=auth[0];__NR.coop.setAgent(a.agentId,{skillCD:0});let st=await call('nr_observe');await new Promise(r=>setTimeout(r,90));const first=await call('nr_command',{...a,runId:st.runId,seq:2,tactic:'guard',autoSkills:false,cast:'skill'});await new Promise(r=>setTimeout(r,90));const second=await call('nr_command',{...a,runId:st.runId,seq:3,tactic:'guard',autoSkills:false,cast:'skill'});check(first.cast==='executed','first skill failed');check(second.cast==='cooldown','cooldown bypassed');return{first:first.cast,second:second.cast,humanCD:__NR.snapshot().stats.skillCD};}''')
  test('Orders expire to guard, heartbeat lease falls back locally','''async()=>{const a=auth[0];await new Promise(r=>setTimeout(r,80));let st=await call('nr_observe');const r=await call('nr_command',{...a,runId:st.runId,seq:4,tactic:'hold',x:30,y:40,duration:1,autoSkills:false});check(r.ok,'expiry order failed');__NR.advance(1.2);let u=__NR.coop.observe().units.find(u=>u.id===a.agentId);check(u.tactic==='guard','order did not expire');__NR.coop.lease(a.agentId);u=__NR.coop.observe().units.find(u=>u.id===a.agentId);check(u.stale,'lease did not expire');const hb=await call('nr_heartbeat',a);check(hb.ok&&!__NR.coop.observe().units.find(u=>u.id===a.agentId).stale,'heartbeat failed');return{expired:u.tactic,leaseStale:u.stale,heartbeat:hb.ok};}''')
  test('Leaving revokes token, current boss HP unchanged','''async()=>{__NR.spawnBoss(0);const hp=__NR.coop.bossHP(),scale=__NR.coop.observe().scaling;const r=await call('nr_leave',auth[2]);check(r.ok,'leave failed');const denied=await call('nr_heartbeat',auth[2]);check(!denied.ok,'old token usable');check(__NR.coop.bossHP()===hp,'boss HP dropped');check(__NR.coop.observe().scaling.agents===3,'wave scale dropped');return{bossHP:hp,retainedScale:scale,tokenRejected:true};}''')
  test('Midwave join waits; next wave deploys; lower scale next boundary','''async()=>{const rejoin=await call('nr_join',{slot:3,name:'RECONNECT'});check(rejoin.ok&&rejoin.pending,'midwave not pending');check(__NR.coop.observe().units.length===3,'early deploy');auth[2]={agentId:rejoin.agentId,token:rejoin.token};__NR.wave(3);check(__NR.coop.observe().units.length===4,'no deployment');await call('nr_leave',auth[2]);__NR.wave(5);const r=__NR.coop.observe();check(r.units.length===3&&r.scaling.agents===2&&r.scaling.bossHP===2.3,'boundary scaling wrong');return{units:r.units.length,scaling:r.scaling};}''')
  test('Shared XP levels; separate build preferences','''()=>{const before=__NR.coop.observe().units.map(u=>u.level);__NR.coop.level();const after=__NR.coop.observe().units.map(u=>u.level);check(after.every((x,i)=>x===before[i]+1),'XP not shared');return{before,after};}''')
  test('Paused simulation rejects combat commands and stays still','''async()=>{__NR.pause();let a=__NR.coop.observe();__NR.advance(3);const bb=__NR.coop.observe();check(a.time===bb.time&&JSON.stringify(a.units)===JSON.stringify(bb.units),'pause moved units');const r=await call('nr_command',{...auth[0],runId:a.runId,seq:5,tactic:'guard'});check(!r.ok&&r.error==='NOT_PLAYING','command accepted paused');__NR.resume();return{time:a.time,rejected:r.error};}''')
  test('Human downed can be rescued; no instant solo loss in party','''()=>{__NR.start({hero:0,mode:'endless',difficulty:0});__NR.coop.clear();__NR.setPlayer({x:0,y:0});const ids=__NR.coop.observe().units.filter(u=>u.id!=='human').map(u=>u.id);for(let i=0;i<ids.length;i++)__NR.coop.setAgent(ids[i],{x:20+i*10,y:0,order:{tactic:'hold',x:0,y:0,autoSkills:false,until:100},nextThink:10,mx:0,my:0,inv:100});__NR.coop.hurt('human',9999);check(__NR.snapshot().state==='play'&&__NR.coop.observe().units[0].downed,'instant loss');__NR.advance(2.1);const r=__NR.coop.observe();check(!r.units[0].downed&&r.units[0].hp>0,'human not revived by seraph');return{hp:r.units[0].hp,rescues:__NR.coop.raw().rescues};}''')
  test('Companion takes damage; human rescues companion','''()=>{__NR.coop.clear();const u=__NR.coop.observe().units[1];__NR.setPlayer({x:u.x,y:u.y,inv:100});__NR.coop.hurt(u.id,9999);check(__NR.coop.observe().units[1].downed,'companion immortal');__NR.advance(2.5);check(!__NR.coop.observe().units[1].downed,'companion not rescued');return{rescues:__NR.coop.raw().rescues};}''')
  test('Party wipe fails the operation','''()=>{for(const u of __NR.coop.observe().units)__NR.coop.hurt(u.id,99999);check(__NR.snapshot().state==='result','party wipe did not fail');return __NR.snapshot().state;}''')
  test('New run identity invalidates old run commands','''async()=>{const old=(await call('nr_observe')).runId;__NR.start({invincible:true});const r=await call('nr_command',{...auth[0],runId:old,seq:500,tactic:'guard'});check(!r.ok&&r.error==='STALE_RUN','stale run accepted');return{stale:r.error};}''')
  test('All six classes work as companions','''()=>{const rows=[];for(let hero=0;hero<6;hero++){__NR.coop.config(1,'bot',hero);__NR.coop.config(2,'off',4);__NR.coop.config(3,'off',5);__NR.start({hero:(hero+1)%6,mode:'bossrush',difficulty:0,invincible:true});__NR.advance(2);const a=__NR.coop.observe().units[1];__NR.coop.setAgent(a.id,{skillCD:0,ult:100});__NR.advance(3);const r=__NR.coop.raw();check(r.units[1].damage>0,'no damage for class '+hero);check(__NR.verify().length===0,'invalid state');rows.push({hero,damage:r.units[1].damage,skillCooldown:r.units[1].cooldowns.skill});}return rows;}''')
  test('Eight bosses attack/enrage and render without GPU errors','''()=>{const rows=[];for(let type=0;type<8;type++){__NR.start({hero:0,mode:'endless',difficulty:0,invincible:true});__NR.spawnBoss(type);__NR.advance(3);__NR.bossPhase();__NR.advance(2);const st=__NR.snapshot();check(st.boss?.phase===1,'no enrage '+type);__NR.render();check(document.querySelector('#game').getContext('webgl2').getError()===0,'GPU failure');check(__NR.verify().length===0,'pool corruption');rows.push({type,phase:st.boss.phase,attacks:st.boss.attacks,warnings:st.warnings});}return rows;}''')
  test('Boss rush clears all eight bosses','''()=>{__NR.start({mode:'bossrush',difficulty:0,invincible:true});__NR.advance(2);const seq=[];for(let i=0;i<8;i++){seq.push(__NR.snapshot().boss?.type);__NR.defeatBoss();__NR.advance(3.7);}check(__NR.snapshot().state==='result'&&__NR.snapshot().bosses===8,'no victory');return{seq,bosses:__NR.snapshot().bosses};}''')
  test('Campaign and endless progression preserved','''()=>{__NR.start({mode:'campaign',invincible:true});__NR.wave(16);__NR.advance(3.2);__NR.defeatBoss();check(__NR.snapshot().state==='result','campaign did not finish');__NR.start({mode:'endless',invincible:true});__NR.wave(16);__NR.advance(3.2);__NR.defeatBoss();__NR.advance(37);check(__NR.snapshot().wave>16&&__NR.snapshot().state==='play','endless stopped');return{endlessWave:__NR.snapshot().wave};}''')
  test('1442-enemy pool stress with three companions','''()=>{for(let i=1;i<=3;i++)__NR.coop.config(i,'bot',i+1);__NR.start({mode:'endless',hero:3,difficulty:3,invincible:true});__NR.saturate(1442);const peak=__NR.snapshot().enemies;__NR.setPlayer({ult:100});__NR.ultimate();__NR.advance(2.5);check(__NR.verify().length===0,'pool invalid');check(__NR.coop.raw().units.length===4,'lost companion');return{peak,valid:__NR.verify(),blades:__NR.snapshot().blades};}''')
  test('Language hot switch and English visible-text scan','''()=>{__NR.pause();let a=__NR.coop.observe();__NR.lang('zh');check(document.getElementById('hudName').textContent==='虚空工匠'||document.documentElement.lang==='zh-CN','translation');__NR.lang('en');const bb=__NR.coop.observe();check(a.time===bb.time&&a.runId===bb.runId,'language reset game');const scans=[];for(const view of['home','select','inspect']){if(view==='home')__NR.home();if(view==='select')__NR.select();if(view==='inspect')__NR.inspect(6);__NR.render();let cjk=document.body.innerText.match(/[\u3400-\u9fff]+/g)||[];check(cjk.length===0,'English screen has CJK: '+cjk);scans.push({view,cjk});}return scans;}''')
  test('Canvas compatibility preserves gameplay and full resolution','''()=>{__NR.closeInspect();__NR.backend('canvas');__NR.start({mode:'bossrush',invincible:true});__NR.advance(.5);__NR.render();const r=__NR.snapshot().renderer;check(r.backend==='Canvas 2D'&&r.resolution[0]>=640,'bad fallback');check(__NR.coop.observe().units.length===4,'fallback lost party');__NR.backend('auto');return r;}''')
  # Native registration mocked, not a claim of E2E real WebMCP support.
  p2=browser.new_page(viewport={'width':800,'height':500})
  p2.evaluate("window.mockTools=new Map();Object.defineProperty(document,'modelContext',{value:{registerTool:async(t,o)=>{window.mockTools.set(t.name,t);o.signal.addEventListener('abort',()=>window.mockTools.delete(t.name));}}});")
  p2.set_content(html);p2.wait_for_function('!!window.__NR && window.mockTools.size===7')
  try:
   r=p2.evaluate("async()=>{const tools=[...mockTools.values()];let r=JSON.parse(await mockTools.get('nr_observe').execute({},{}));return{names:tools.map(t=>t.name),resultOK:r.ok,bridge:r.bridge,readOnly:mockTools.get('nr_observe').annotations.readOnlyHint};}")
   assert r['resultOK'] and len(r['names'])==7 and r['readOnly'];results.append({'test':'Modern document.modelContext registration contract (mock)','passed':True,'details':r})
  except Exception as e:results.append({'test':'Modern registration contract (mock)','passed':False,'error':str(e)})
  p2.close()
  results.append({'test':'No uncaught browser script errors','passed':not errors,'details':errors})
  (ROOT/'tests/test_results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2),encoding='utf8')
  print('SUMMARY',sum(x['passed'] for x in results),'/',len(results),flush=True);browser.close()
try:run()
finally:
 if display:display.terminate()
