/* 离线生成的管风琴/合唱垫底 + 合成器脉冲，最多16个音效声部。 */
class NRAudio {
 constructor(options){this.options=options;this.ctx=null;this.muted=false;this.paused=false;this.current='music_menu';this.nodes=new Set();this.last={};this.errors=[];this.loops={};this.mix='musicCalm';this.started=false;this.serial=0;}
 get voices(){return this.nodes.size;}
 async prepare(){return true;}
 init(){try{if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();const c=this.ctx;this.master=c.createDynamicsCompressor();this.master.threshold.value=-15;this.master.ratio.value=4;this.master.connect(c.destination);this.musicBus=c.createGain();this.musicBus.connect(this.master);this.bus=c.createGain();this.bus.connect(this.master);this.buffers={};this.makeScore();this.makeSfx();this.started=true;}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});this.update();}catch(e){this.errors.push(String(e));}}
 makeScore(){const c=this.ctx,sr=22050,dur=20,steps=32,beat=dur/steps;const rnd=(n)=>Math.sin(n*132.75+18.13)*43758.5453%1;for(const key of ['bed','pulse','drums','boss']){const buffer=c.createBuffer(2,sr*dur,sr);for(let ch=0;ch<2;ch++){const a=buffer.getChannelData(ch);for(let n=0;n<a.length;n++){let t=n/sr,st=Math.floor(t/beat),bt=t%beat/beat,v=0;const root=[110,87.307,130.813,98][Math.floor(st/8)%4];if(key==='bed'){for(const r of [1,1.5,2,2.3784])v+=(Math.sin(t*6.28318*root*r+ch*.2)+.23*Math.sin(t*6.28318*root*r*2.002))*.037;v*=.75+.25*Math.sin(t*Math.PI/5)**2;}else if(key==='pulse'){const note=[1,2,1.5,2.3784,1,1.5,2,3][st%8],fr=root*note*2;v=(Math.sin(t*6.28318*fr)+.22*Math.sin(t*6.28318*fr*2))*Math.exp(-bt*7)*.14;}else if(key==='drums'){v=Math.sin(6.28318*(42*t+8*(1-Math.exp(-bt*12))))*Math.exp(-bt*12)*.34;const hat=(rnd(n*1.77)-rnd(n*.72));v+=hat*Math.exp(-(t%(beat/2))/(beat/2)*28)*.12;if(st%4===2)v+=rnd(n*.71)*Math.exp(-bt*17)*.18;}else{v=(Math.sin(t*root*6.28318*.5)+.15*Math.sin(t*root*6.28318*1.5))*.12*(.7+.3*Math.sin(t*Math.PI/5));v+=Math.sin(t*root*6.28318*4)*Math.exp(-bt*6)*.035;}const fade=Math.min(1,t/.05,(dur-t)/.05);a[n]=v*fade;}}const s=c.createBufferSource(),g=c.createGain();s.buffer=buffer;s.loop=true;g.gain.value=0;s.connect(g);g.connect(this.musicBus);s.start();this.loops[key]={s,g};}this.profile();}
 makeSfx(){const c=this.ctx,sr=22050;const configs={shot:[.13,800,240,.13],hit:[.14,240,65,.5],armor:[.2,1000,140,.52],heavy:[.35,130,34,.7],dash:[.24,190,850,.35],pickup:[.16,700,1100,.2],level:[.8,440,880,.28],hurt:[.3,150,45,.55],skill:[.6,300,60,.5],ultimate:[1.25,70,350,.54],boss:[1.35,105,44,.4],block:[.25,640,80,.55],win:[1.5,330,660,.26],fail:[1.2,220,60,.3],kill:[.1,330,90,.3]};for(const [name,[dur,f1,f2,power]] of Object.entries(configs)){const b=c.createBuffer(1,Math.ceil(dur*sr),sr),d=b.getChannelData(0);let phase=0;for(let i=0;i<d.length;i++){let t=i/sr,u=t/dur;phase+=6.28318*(f1+(f2-f1)*u)/sr;let noise=(Math.random()*2-1)*(name==='armor'?.65:name==='dash'?.4:.13);d[i]=(Math.sin(phase)+.25*Math.sin(phase*2.01)+noise)*Math.sin(Math.PI*Math.min(1,u*15))*Math.exp(-u*4.5)*power;}this.buffers[name]=b;}}
 profile(){if(!this.ctx)return;let w=this.current==='music_menu'?[.9,.13,0,0]:this.mix==='musicBoss'?[.5,.65,.8,.8]:this.mix==='musicDanger'?[.6,.85,.9,.2]:this.mix==='musicRise'?[.8,.52,.48,0]:[.9,.22,.18,0];Object.values(this.loops).forEach((v,i)=>v.g.gain.setTargetAtTime(w[i],this.ctx.currentTime,.8));}
 music(name){this.paused=false;this.current=name;this.mix=name==='music_boss'?'musicBoss':name==='music_menu'?'musicCalm':'musicRise';this.profile();this.update();}
 battle(p,boss,phase,hp,ult){const mix=boss?'musicBoss':p>.55||hp<.25||ult?'musicDanger':p>.18||phase===2?'musicRise':'musicCalm';if(mix!==this.mix){this.mix=mix;this.profile();}}
 update(){if(!this.ctx)return;this.musicBus.gain.setTargetAtTime(this.muted?0:(this.options.music??.24)*(this.paused?.25:1),this.ctx.currentTime,.06);this.bus.gain.setTargetAtTime(this.muted?0:this.options.sfx??.55,this.ctx.currentTime,.03);const el=document.getElementById('muteBtn');if(el)el.textContent=this.muted?'♪̸':'♫';}
 pause(v){this.paused=v;this.update();}
 sfx(name,pan=0,power=1){const c=this.ctx;if(!c||c.state!=='running'||this.muted||this.nodes.size>=16||!this.buffers[name])return;let limit={shot:.17,hit:.08,kill:.15,armor:.1,pickup:.09}[name]||.08;if(c.currentTime-(this.last[name]??-20)<limit)return;this.last[name]=c.currentTime;const s=c.createBufferSource(),g=c.createGain(),p=c.createStereoPanner();s.buffer=this.buffers[name];s.playbackRate.value=.95+(this.serial++%5)*.025;g.gain.value=power;p.pan.value=Math.max(-1,Math.min(1,pan));s.connect(g);g.connect(p);p.connect(this.bus);this.nodes.add(s);s.onended=()=>{this.nodes.delete(s);s.disconnect();g.disconnect();p.disconnect();};s.start();}
 info(){return{context:this.ctx?.state||'not-started',mix:this.mix,voices:this.voices,muted:this.muted,playing:this.started,errors:this.errors};}
}
