    let oathChain=null,oathProofStoreError=null;
    const oathProofDrafts=new Map();
    const oathProofVerified=new Map();
    function oathProofs(){let records=[];try{records=NRProvenance.list(localStorage);oathProofStoreError=null;}catch(e){oathProofStoreError=e;}for(const pkg of oathProofDrafts.values()){const i=records.findIndex(p=>NRProvenance.key(p)===NRProvenance.key(pkg));if(i<0)records.push(pkg);else records[i]=pkg;}return records;}
    function oathKeepProof(pkg){const proof=NRProvenance.validate(pkg);try{const saved=NRProvenance.save(localStorage,proof);oathProofDrafts.set(NRProvenance.key(saved),saved);return true;}catch(e){if(e.message.includes('CONFLICT'))throw e;oathProofDrafts.set(NRProvenance.key(proof),proof);return false;}}
    async function oathVerifyProof(pkg){
      const candidate=NRProvenance.validate(pkg),p=candidate.proof,v=await oathChain.readCircuit(p.processor,p.circuitId);
      const evidence=await oathChain.receiptEvidence(p.processor,p.circuitId,p.txHash,v);
      const rebuilt=NRProvenance.make(evidence,{blueprint:candidate.work.blueprint,parent:candidate.work.parent?.id,parentNetlistHash:candidate.work.parent?.netlistHash});
      if(NRProvenance.canonical(rebuilt.proof)!==NRProvenance.canonical(p)||NRProvenance.canonical(rebuilt.work)!==NRProvenance.canonical(candidate.work))throw Error('CHAIN_PROVENANCE_MISMATCH');
      oathProofVerified.set(NRProvenance.key(candidate),{block:v.block,owner:v.owner});return{pkg:candidate,v};
    }
    function oathForge(){
      const body=$('oathBody');if(!oathChain)oathChain=new NRXLayer.Adapter({ethereum:window.ethereum,storage:localStorage});
      body.append(oe('p','o-intro',oathText('Edit → test → obtain NAND/LATCH → tape out → read back → equip. Every gate in the final netlist counts as material. Gameplay runs the verified bytes locally; it does not send transactions every frame.','编辑 → 试验 → 获取 NAND/LATCH → 流片 → 读回 → 装备。最终网表中的每个门都计入材料。战斗在本地执行校验后的网表，不逐帧发送交易。')));
      const official=oe('a','o-link',oathText('Open the official TapeOut canvas ↗','打开 TapeOut 官方画布 ↗'));official.href='https://tapeout.net';official.target='_blank';official.rel='noopener noreferrer';body.append(official);
      const featuredCPU='0x57E9e1111f42F448126A9F12b2b3f99a79dd1A44';
      const cpu=oi(featuredCPU,42);cpu.placeholder='0x…';const id=oi('1',20),featured=os(OC.PRESETS.map((p,i)=>[String(i+1),'#'+(i+1)+' · '+oathText(p.en,p.zh)]),'1',v=>{cpu.value=featuredCPU;id.value=v;});
      const read=oe('section','o-forge-block');read.append(oe('h3','',oathText('Read a manufactured circuit · Nandverse Foundry','读回已制造芯片 · Nandverse Foundry')),of(oathText('Featured on-chain chip','已流片的演示芯片'),featured),of(oathText('X Layer processor address','X Layer 处理器地址'),cpu),of(oathText('Circuit ID','芯片编号'),id));
      const progress=oe('pre','o-netlist');progress.setAttribute('role','status');
      const output=e=>{progress.textContent+=(progress.textContent?'\n':'')+e.label+' · '+e.status+' · '+e.hash;};
      async function action(fn){if(OUI.forgeBusy)return;OUI.forgeBusy=true;const controls=[...body.querySelectorAll('button,input,select,textarea')];controls.forEach(x=>x.disabled=true);try{await fn();}catch(e){oathError(e);progress.textContent=oathText('Stopped: ','操作已停止：')+(e.shortMessage||e.message)+(e.hash?'\n'+e.hash:'');}finally{OUI.forgeBusy=false;controls.forEach(x=>x.disabled=false);refreshProofs();}}
      function install(v){
        const record=OD.normalizeCircuitRecord({id:'xl-'+v.address.slice(2).toLowerCase()+'-'+v.id,name:'TapeOut #'+v.id,note:'Verified NAND/LATCH readback',source:{type:'xlayer',chainId:196,processor:v.address,circuitId:v.id,block:v.block},circuit:v.c});
        const p=OATH.profile,idx=p.library.findIndex(r=>r.id===record.id);if(idx<0){if(p.library.length>=100)throw Error('LIBRARY_LIMIT');p.library.push(record);}else p.library[idx]=record;
        OATH.verified.set(record.id,{hash:v.hash,block:v.block});oathSave();OUI.selected=record.id;
        progress.textContent=oathText('Verified and added to library. Equip from Squad.','校验完成，已加入蓝图库。可在队伍页装备。')+'\n'+v.address+' #'+v.id+'\nBlock '+v.block+'\n'+v.hash+'\n'+v.c.nNand+' NAND + '+v.c.nLatch+' LATCH';return record;
      }
      read.append(ob(oathText('Verify and import · read only','校验并导入 · 只读'),()=>action(async()=>{progress.textContent=oathText('Reading provenance, bytes and execution…','正在读取来源、网表与执行结果……');install(await oathChain.readCircuit(cpu.value.trim(),id.value.trim()));}),'primary'));body.append(read);
      const mint=oe('section','o-forge-block');mint.append(oe('h3','',oathText('Manufacture a saved version','制造已保存版本')));
      const blueprint=os(OD.list(OATH.profile).map(r=>[r.id,oathName(r)]),OUI.selected),quoteOut=oe('pre','o-netlist');let quote=null;
      mint.append(of(oathText('Saved blueprint · edit and save before quoting','已存蓝图 · 编辑后请先保存再报价'),blueprint),ob(oathText('Connect wallet / X Layer','连接钱包 / X Layer'),()=>action(async()=>{const account=await oathChain.connect();oathNotice(oathText('Connected ','已连接 ')+account);quote=null;})));
      const buildQuote=ob(oathText('Read material and fee quote','读取材料与费用报价'),()=>action(async()=>{const r=OD.find(OATH.profile,blueprint.value);quote=await oathChain.quote(cpu.value.trim(),r.circuit,oathChain.account);quoteOut.textContent=quote.c.nNand+' NAND + '+quote.c.nLatch+' LATCH · '+quote.c.bytes+' bytes\n'+oathText('Missing material: ','待补材料：')+quote.need[0]+' NAND / '+quote.need[1]+' LATCH\n'+oathText('Material price: ','材料单价：')+NRXLayer.format(quote.price)+' OKB\n'+oathText('Protocol fee per mint: ','每次铸造协议费：')+NRXLayer.format(quote.protocol)+' OKB\n'+oathText('Tapeout fee: ','流片费：')+NRXLayer.format(quote.fee)+' OKB\n'+oathText('Total before gas: ','合计（不含 Gas）：')+NRXLayer.format(quote.total)+' OKB\n'+oathText(quote.account?'Wallet balance included.':'No wallet: assumes no materials owned.',quote.account?'已考虑钱包现有材料。':'未连接钱包：按没有材料计算。');}));mint.append(buildQuote,quoteOut);
      const confirm=oe('input');confirm.type='checkbox';mint.append(of(oathText('I reviewed this quote. Continue with paid wallet confirmations.','我已核对以上报价，继续进行付费钱包确认。'),confirm),ob(oathText('Mint material and tape out','铸造材料并流片'),()=>action(async()=>{if(!confirm.checked||!quote)throw Error('REVIEW_QUOTE_FIRST');const source=OD.find(OATH.profile,blueprint.value);if(quote.c.netlist!==source.circuit.netlist||quote.address.toLowerCase()!==cpu.value.trim().toLowerCase())throw Error('QUOTE_CHANGED_REVIEW_AGAIN');confirm.checked=false;const v=await oathChain.manufacture(quote,output);const parent=source.parent?OD.find(OATH.profile,source.parent):null;const pkg=NRProvenance.make(v.evidence,{blueprint:source.blueprint,parent:parent?.id,parentNetlistHash:parent?ethers.keccak256(parent.circuit.netlist):null});oathKeepProof(pkg);install(v);quote=null;progress.textContent+='\n'+oathText('Publication proof saved. Sign your authorship claim below, then export the certificate.','发布凭证已保存。请在下方签署作者声明，再导出凭证。');}),'primary'));
      body.append(mint);
      const deployment=oe('details','o-forge-block'),summary=oe('summary','',oathText('Create a new processor for the competition','为参赛创建新的处理器'));deployment.append(summary);
      const name=oi('',48),symbol=oi('',12),story=oi('',500),supply=oi('',18),price=oi('',30);name.placeholder=oathText('Enter project processor name','填写项目处理器名称');symbol.placeholder=oathText('Enter material symbol','填写材料简称');story.placeholder=oathText('Describe the processor and its use','说明处理器及其用途');supply.placeholder=oathText('Enter a fixed public supply','输入公开供应上限');price.placeholder=oathText('Price per gate in OKB','每门材料的 OKB 单价');
      for(const [label,input]of [[oathText('Name','名称'),name],[oathText('Symbol','符号'),symbol],[oathText('Story','说明'),story],[oathText('Material supply cap','材料供应上限'),supply],[oathText('Public mint price (OKB)','公开铸造单价（OKB）'),price]])deployment.append(of(label,input));
      let deployQuote=null;const deployPreview=oe('pre','o-netlist'),agree=oe('input');agree.type='checkbox';
      deployment.append(ob(oathText('Review processor creation','核对处理器创建'),()=>action(async()=>{deployQuote=await oathChain.deployQuote({name:name.value,symbol:symbol.value,story:story.value,supply:supply.value,price:price.value});deployPreview.textContent=deployQuote.name+' / '+deployQuote.symbol+'\nSupply '+deployQuote.supply+' · '+NRXLayer.format(deployQuote.price)+' OKB / gate\n'+oathText('Creation fee: ','创建费用：')+NRXLayer.format(deployQuote.fee)+' OKB + Gas\n'+oathText('Public immutable supply and price.','公开且固定的供应量与单价。');})),deployPreview,of(oathText('I accept these exact public parameters and fee.','我同意上述具体公开参数与费用。'),agree),ob(oathText('Create with wallet confirmation','通过钱包确认创建'),()=>action(async()=>{if(!agree.checked||!deployQuote)throw Error('REVIEW_DEPLOYMENT_FIRST');const q=deployQuote;if(name.value!==q.name||symbol.value!==q.symbol||story.value!==q.story||String(q.supply)!==supply.value||NRXLayer.format(q.price)!==NRXLayer.format(ethers.parseEther(price.value)))throw Error('PARAMETERS_CHANGED');agree.checked=false;const result=await oathChain.deploy(q,output);cpu.value=result.address;deployQuote=null;oathNotice(oathText('Processor created: ','处理器已创建：')+result.address);}),'primary'));
      body.append(deployment);
      const provenance=oe('section','o-forge-block');provenance.append(oe('h3','',oathText('Author provenance certificates','作者归属凭证')),oe('p','o-small',oathText('The event proves who published the circuit. A wallet signature records an authorship declaration; it does not adjudicate originality. Proofs are separate from the 30 recent transaction links.','链上事件证明发布钱包。钱包签名记录作者声明，但不裁定原创。凭证独立于最近30条交易链接保存。')));
      const proofSelect=oe('select'),proofList=oe('div','o-proof-list'),claimRole=os(NRProvenance.roles.map(role=>[role,role]),'author'),claimNote=oi('',200),royalty=oi('',42),tx=oi('',70),importText=oe('textarea');
      claimNote.placeholder=oathText('Optional: commission, collaborators, adaptation and permission context','可选：委托、联合作者、改编及授权说明');royalty.placeholder=oathText('Optional proposed royalty wallet','可选：建议版税收款钱包');tx.placeholder='0x…';importText.rows=5;importText.maxLength=NRProvenance.MAX_PACKAGE;importText.placeholder=oathText('Paste a provenance certificate JSON','粘贴作者凭证 JSON');importText.setAttribute('aria-label',importText.placeholder);
      function selectedProof(){const pkg=oathProofs().find(p=>NRProvenance.key(p)===proofSelect.value);if(!pkg)throw Error('SELECT_PROVENANCE_FIRST');return pkg;}
      function refreshProofs(){
        try{const all=oathProofs(),choice=proofSelect.value;proofSelect.replaceChildren();for(const p of all){const k=NRProvenance.key(p);proofSelect.add(new Option(p.proof.processor.slice(0,10)+' #'+p.proof.circuitId+' · '+p.claims.length+' '+oathText('claims','项声明'),k,false,k===choice));}proofList.replaceChildren();
          for(const p of all){const k=NRProvenance.key(p),checked=oathProofVerified.get(k),line=oe('div','o-proof-entry');line.append(oe('strong','',p.proof.processor.slice(0,12)+' #'+p.proof.circuitId),oe('span','',checked?oathText('Chain verified this session','本会话已读链校验'):oathText('Stored claim · re-verify chain','已存声明 · 需重新读链')),oe('small','',oathText('Published by ','发布钱包 ')+p.proof.publisher+(checked?' · '+oathText('Current owner ','当前持有人 ')+checked.owner:'')),oe('small','',oathText('Signed claims ','已签声明 ')+(p.claims.map(c=>c.role+' '+c.signer.slice(0,10)).join(', ')||oathText('none','无'))));proofList.append(line);}
          if(oathProofStoreError){const backup=ob(oathText('Export unreadable local proof store','导出无法读取的本地凭证库'),()=>oathDownload('oath-provenance-store-backup.txt',localStorage.getItem(NRProvenance.KEY)||''));proofList.append(oe('p','o-small',oathText('Local proof store needs recovery: ','本地凭证库需要恢复：')+oathProofStoreError.message),backup);}
          if(!all.length)proofList.append(oe('p','o-small',oathText('No certificate yet. Tape out a chip or reconstruct from its original transaction.','暂无凭证。可流片制造，或用原始交易哈希补建。')));
          if(oathProofDrafts.size)proofList.append(oe('p','o-small',oathText('Export a copy for long-term backup. If browser storage is blocked, this session copy is your only local copy.','请导出长期备份。若浏览器存储不可写，本会话副本是本机唯一副本。')));
        }catch(e){proofList.replaceChildren(oe('p','o-small',oathText('Provenance store cannot be read: ','作者凭证库读取失败：')+e.message));}
      }
      provenance.append(of(oathText('Saved certificate','已存凭证'),proofSelect),proofList);
      provenance.append(ob(oathText('Verify selected against chain','读链复核所选凭证'),()=>action(async()=>{const{pkg,v}=await oathVerifyProof(selectedProof());install(v);progress.textContent=oathText('Certificate verified: publisher and immutable netlist match the original event.','凭证已核验：发布者和固定网表与原始事件一致。')+'\n'+pkg.proof.txHash;})),ob(oathText('Export selected certificate','导出所选凭证'),()=>oathDownload('oath-provenance-'+selectedProof().proof.circuitId+'.json',NRProvenance.exportPackage(selectedProof()),'application/json')));
      provenance.append(of(oathText('Your signed role','你签署的角色'),claimRole),of(oathText('Declaration details','声明说明'),claimNote),of(oathText('Proposed royalty recipient','建议版税收款方'),royalty));
      provenance.append(ob(oathText('Sign selected claim with wallet','用钱包签署所选声明'),()=>action(async()=>{const{pkg}=await oathVerifyProof(selectedProof()),signer=await oathChain.connect(),fields={signer,role:claimRole.value,note:claimNote.value,royaltyRecipient:royalty.value.trim()||null},message=NRProvenance.statement(pkg,fields),signature=await oathChain.signStatement(message,signer),signed=NRProvenance.addClaim(pkg,fields,signature),persisted=oathKeepProof(signed);progress.textContent=oathText('Claim signed. Export this certificate.','声明已签署，请导出凭证。')+(persisted?'':'\n'+oathText('Browser storage unavailable; export now.','浏览器存储不可用，请立即导出。'));}),'primary'));
      provenance.append(of(oathText('Original tapeout transaction (for older chips)','旧芯片原始流片交易哈希'),tx),ob(oathText('Rebuild proof from original event','从原始事件补建凭证'),()=>action(async()=>{const v=await oathChain.readCircuit(cpu.value.trim(),id.value.trim()),evidence=await oathChain.receiptEvidence(v.address,v.id,tx.value.trim(),v),existing=oathProofs().find(p=>p.proof.processor.toLowerCase()===v.address.toLowerCase()&&p.proof.circuitId===v.id);let pkg;if(existing){if(existing.proof.txHash.toLowerCase()!==evidence.txHash.toLowerCase())throw Error('PROVENANCE_CONFLICT');pkg=(await oathVerifyProof(existing)).pkg;}else{let source=OD.list(OATH.profile).find(r=>r.source.type==='xlayer'&&r.source.processor.toLowerCase()===v.address.toLowerCase()&&String(r.source.circuitId)===v.id);if(source?.blueprint&&OC.compile(source.blueprint).netlist!==v.c.netlist)source=null;const parent=source?.parent?OD.find(OATH.profile,source.parent):null;pkg=NRProvenance.make(evidence,{blueprint:source?.blueprint,parent:parent?.id,parentNetlistHash:parent?ethers.keccak256(parent.circuit.netlist):null});}const persisted=oathKeepProof(pkg);install(v);progress.textContent=oathText('Original chain event verified; now sign a declaration and export.','原始链上事件已核验；请签署声明并导出。')+(persisted?'':'\n'+oathText('Browser storage unavailable; export now.','浏览器存储不可用，请立即导出。'));})));
      provenance.append(importText,ob(oathText('Import and verify certificate','导入并核验凭证'),()=>action(async()=>{const pkg=NRProvenance.parse(importText.value),checked=await oathVerifyProof(pkg),persisted=oathKeepProof(checked.pkg);install(checked.v);progress.textContent=oathText('Imported certificate verified on chain.','导入凭证已完成链上核验。')+(persisted?'':'\n'+oathText('Browser storage unavailable; export now.','浏览器存储不可用，请立即导出。'));})));
      const file=oe('input');file.type='file';file.accept='.json';file.setAttribute('aria-label',oathText('Import certificate file','导入凭证文件'));file.onchange=()=>action(async()=>{const f=file.files[0];if(!f||f.size>NRProvenance.MAX_PACKAGE)throw Error('PACKAGE_TOO_LARGE');const pkg=NRProvenance.parse(await f.text()),checked=await oathVerifyProof(pkg),persisted=oathKeepProof(checked.pkg);install(checked.v);progress.textContent=oathText('Imported certificate verified on chain.','导入凭证已完成链上核验。')+(persisted?'':'\n'+oathText('Browser storage unavailable; export now.','浏览器存储不可用，请立即导出。'));});provenance.append(file);
      body.append(provenance,progress,oe('p','o-small',oathText('Keep transaction hashes if a network call times out. Check the explorer before retrying; a pending transaction is not a failure. Mainnet scoring and ownership do not make local combat cheat-proof.','网络超时请保留交易哈希，先在浏览器确认状态再重试；待确认交易不等于失败。链上来源不代表本地战斗不可作弊。')));refreshProofs();
      let history=[];try{history=JSON.parse(localStorage.getItem('nr.oath.transactions')||'[]');}catch{}if(Array.isArray(history))for(const item of history.slice(-5)){if(!/^0x[\da-f]{64}$/i.test(item.hash))continue;const link=oe('a','o-link',String(item.label)+' · '+String(item.status)+' · '+item.hash.slice(0,14));link.href='https://www.oklink.com/xlayer/tx/'+item.hash;link.target='_blank';link.rel='noopener noreferrer';body.append(link);}
    }
