    /* 直接展示战场使用的同一份模型；拖动旋转不影响游戏模拟。 */
    const BOSS_FORM=[
      ['FURNACE / REGALIA','A vented furnace chest, a seven-point crown and a great execution blade. Brass fasteners connect the plates; heat glows through the rib grilles.','熔炉 / 王权','通风式熔炉胸腔、七尖王冠与处刑巨刃。黄铜铆钉连接层叠甲片，热光从肋状格栅中透出。'],
      ['BONE / WING','An articulated reptilian skull, a long vertebral neck and tail, four load-bearing legs and a pair of membrane wings. Not a knight wearing horns.','白骨 / 龙翼','爬行类颅骨、长节颈与脊尾、四条承重肢以及一对膜翼。它是一头龙，而非戴角头盔的骑士。'],
      ['MASS / HYDRAULICS','A low, armored quadruped. Layered dorsal plating, ram horns and piston-driven legs make its charging silhouette unmistakable.','重甲 / 液压','低重心装甲四足兽。层叠背甲、撞角与液压式关节支撑厚重躯体，轮廓对应它的冲撞攻击。'],
      ['BONE / COMMAND','A hollow rib cage under ceremonial armor, a crowned skull, a tattered command standard and a long polearm. A military silhouette rather than a generic monster.','白骨 / 军令','仪式铠甲下露出空洞肋骨，骷髅戴冠，残损军旗与长柄兵刃组成鲜明的统帅轮廓。'],
      ['REACTOR / ARTILLERY','Six articulated supports surround a concentric reactor. A suspended armored carriage carries twin barrels beneath an ancient mechanical aureole.','反应堆 / 炮阵','六条关节支腿环绕同心反应堆，悬置装甲机架承载双联炮管，背后是古老的机械光环。'],
      ['ABSENCE / PROPHECY','A levitating hooded figure inside a broken shrine. Its face is a dark void, framed by a luminous negative-space ring and suspended relics.','虚空 / 预言','悬浮兜帽身形置于残破神龛，面部是没有五官的黑暗；发光圆环与悬空圣物共同衬托虚空核心。'],
      ['VENOM / TRINITY','Three independently shaped serpent heads rise from distinct curved necks. Visible venom glands and a plated body connect the anatomy.','剧毒 / 三首','三枚不同姿态的蛇首分别连接弯曲长颈。可见毒腺、承重躯体与腹甲让三首结构在视觉上连成整体。'],
      ['ASH / SIX WINGS','Three pairs of articulated wings, layered metallic feathers and a crowned skeletal face. A ceremonial staff anchors its fallen-seraph identity.','灰烬 / 六翼','三对关节羽翼、层叠金属羽片与戴冠骨面构成六翼炽天使；仪式权杖强调堕落圣像的身份。']
    ];
    function refreshInspector(){if(!inspection||!$('inspectName'))return;const i=inspection.id,b=BOSSES[i],f=BOSS_FORM[i],l=language==='en'?0:2;$('inspectIndex').textContent='SOVEREIGN / '+String(i+1).padStart(2,'0')+' — 08';$('inspectName').textContent=b.name;$('inspectSub').textContent=b.sub;$('inspectForm').textContent=f[l];$('inspectDetail').textContent=f[l+1];$('inspectCombat').textContent=b.desc;$('inspectAuto').textContent=coopText(inspection.auto?'AUTO ROTATE · ON':'AUTO ROTATE · OFF',inspection.auto?'自动旋转 · 开':'自动旋转 · 关');$('inspectRotation').value=((inspection.yaw*180/Math.PI)%360+360)%360;$('inspect').style.setProperty('--boss',b.color);}
    function openInspector(id){if(!Number.isInteger(id)||id<0||id>7)return;if(state==='play')pauseGame();inspectionBack=state==='inspect'?inspectionBack:state;inspection={id,yaw:1.05,zoom:1,auto:true};hide('home');hide('select');hide('codexModal');hide('hud');hide('pauseModal');state='inspect';keys.clear();pointer.held=false;coopHUD();show('inspect');refreshInspector();}
    function closeInspector(){hide('inspect');inspection=null;if(inspectionBack==='select')openSelection();else if(inspectionBack==='paused'){state='paused';show('hud');show('pauseModal');coopHUD();}else{refreshHome();show('codexModal');}}
    function initInspector(){Object.assign(UI,{inspectReturn:['← ARCHIVE','← 返回图鉴'],inspectModel:['LIVE GEOMETRY / SAME MODEL IN COMBAT','实时几何 / 与战场相同的模型'],inspectHint:['DRAG TO ROTATE  /  SCROLL TO ZOOM','拖动旋转 / 滚轮缩放'],inspectMorph:['FORM & CONSTRUCTION','形态与结构'],inspectTactics:['COMBAT SIGNATURE','战斗特征'],inspectSelect:['PREVIOUS','上一位'],inspectNext:['NEXT SOVEREIGN →','下一位君主 →']});const s=document.createElement('section');s.id='inspect';s.className='screen hidden';s.innerHTML='<div class="inspect-vignette"></div><header class="inspect-top"><button id="inspectClose" class="quiet" data-i18n="inspectReturn"></button><span data-i18n="inspectModel"></span></header><div class="inspect-reticle"><i></i><i></i><span data-i18n="inspectHint"></span></div><aside class="inspect-panel"><span id="inspectIndex" class="eyebrow"></span><h1 id="inspectName"></h1><p id="inspectSub"></p><div class="inspect-rule"></div><small data-i18n="inspectMorph"></small><h3 id="inspectForm"></h3><p id="inspectDetail"></p><small data-i18n="inspectTactics"></small><p id="inspectCombat"></p><div class="inspect-controls"><input id="inspectRotation" type="range" min="0" max="360" value="24" aria-label="Rotate model"><button id="inspectAuto"></button></div><nav><button id="inspectPrevious" data-i18n="inspectSelect"></button><button id="inspectNext" data-i18n="inspectNext"></button></nav></aside>';$('app').append(s);$('inspectClose').onclick=closeInspector;$('inspectPrevious').onclick=()=>openInspector((inspection.id+7)%8);$('inspectNext').onclick=()=>openInspector((inspection.id+1)%8);$('inspectAuto').onclick=()=>{inspection.auto=!inspection.auto;refreshInspector();};$('inspectRotation').oninput=e=>{inspection.yaw=+e.target.value*Math.PI/180;inspection.auto=false;refreshInspector();};let drag=null;canvas.addEventListener('pointerdown',e=>{if(state==='inspect'){e.preventDefault();drag=e.clientX;canvas.setPointerCapture(e.pointerId);inspection.auto=false;refreshInspector();}});canvas.addEventListener('pointermove',e=>{if(state==='inspect'&&drag!==null){inspection.yaw+=(e.clientX-drag)*.008;drag=e.clientX;refreshInspector();}});window.addEventListener('pointerup',()=>drag=null);window.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{if(state==='inspect'){e.preventDefault();inspection.zoom=clamp(inspection.zoom-e.deltaY*.0006,.72,1.3);}},{passive:false});document.addEventListener('keydown',e=>{if(state==='inspect'&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeInspector();}},true);}
