    /* 直接展示战场使用的同一份模型；拖动旋转不影响游戏模拟。 */
    const BOSS_FORM=[
      ['MAGMA / FURNACE','A molten giant clad in obsidian and black iron, with glowing cracks and massive fists. A molten-gold crown and ember halo rise above a Gothic furnace wall, chimney towers and a chain-hung cloak.','熔岩 / 炉墙','黑曜与铸铁包覆的熔岩巨人，裂缝透出热光，双拳厚重。熔金王冠与余烬光环悬在头后，哥特炉墙、烟囱塔和挂着锁链的披风构成背部轮廓。'],
      ['COIL / ICE WINGS','A levitating mechanical serpent dragon coils beneath a raised chest and neck. Overlapping silver scales, dark ice-blue belly plates and crystal spines lead to an armored jaw and ice-core crown; jointed wings spread five long fingers beneath translucent icy membranes.','盘身 / 冰翼','悬空机械蛇龙盘绕分节躯干，胸颈高高昂起。银色叠瓦鳞、深冰蓝腹板与冰晶背脊延伸到装甲龙颚和冰核王冠；关节翼骨展开五根长指骨，撑起半透明冰蓝翼膜。'],
      ['SIEGE / HYDRAULICS','A four-legged siege beast carries layered blue-steel hull armor, a rotating cannon turret and twin smokestacks. A wedge-shaped ram head, boiler chest, heavy hydraulic legs and a hammer tail complete its industrial silhouette.','攻城 / 液压','四足攻城兽披覆蓝钢叠甲船体，背负可转动炮塔与双烟囱。楔形撞角龙首、胸下锅炉舱、粗壮液压机械腿与锤尾组成重型工业轮廓。'],
      ['BONE / MAINFRAME','A crowned skeletal commander wears bone-white and dark-gold plate around an open rib cage and a layered server heart. Three swallowtail standards rise behind its torn spectral cloak; a flag-bearing polearm completes the command silhouette.','白骨 / 主机','戴冠骷髅统帅身披骨白与暗金重甲，胸甲留窗露出肋笼和多层服务器心核。三面燕尾军旗竖在残破幽灵斗篷后方，旗枪强化军令轮廓。'],
      ['SIX ARMS / AUREOLES','A levitating mechanical deity wears ivory porcelain armor over gilded structure. Six arms hold beam emitters and lens-bearing hands around a solar chest core; a closed-eye mask, three concentric aureoles and hanging segmented plates frame the figure.','六臂 / 光环','悬浮机械神像以象牙瓷甲包覆鎏金结构。六臂上的光束发射器与掌心透镜围绕胸口太阳核心；闭目瓷面、三层同心光环和下垂分节甲片构成圣像轮廓。'],
      ['ALTAR / MANY EYES','A hooded oracle rises from a floating octagonal black-stone altar. A bone-porcelain mask and luminous eye motifs cover the figure; its split hood crown conceals an eye crown, while six obelisk fragments and three void eyes orbit the shrine.','祭坛 / 万眼','兜帽先知从悬浮黑石八棱祭坛上升起。骨瓷面具与发光眼睛纹样遍布身形，可裂开的兜帽冠瓣藏着眼冠；六块方尖碑碎片与三颗虚空眼球环绕祭台公转。'],
      ['VENOM / THREE NECKS','Three armored viper heads rise on long segmented mechanical necks above a low four-legged body. Emerald-black lacquer armor, gilded neck bands, cheek glands and ivory fangs surround luminous venom pipes; three caged reservoirs feed a chest reaction core.','剧毒 / 三颈','三颗装甲蝰蛇头连接长节机械颈，立在低伏四足躯体上。翠黑漆甲、金箍、颊部毒腺与象牙毒牙围住发光毒管；三只金笼储罐接入胸前毒液反应核。'],
      ['ASH / TERMINAL HEART','A giant armored seraph spreads two pairs of layered metal blade wings beneath a burning rune halo and flame crown. Dark-steel plate, gilded petal pauldrons and articulated gauntlets frame a faceted ruby sacred heart; its hands grip a great terminal sword.','灰烬 / 终末圣心','巨型装甲炽天使展开两对层叠金属刃羽翼，头后悬着燃烧符文光环与火舌冠。暗钢板甲、鎏金花瓣肩甲和关节铠甲手衬托刻面红宝石圣心，双手握持终末巨剑。']
    ];
    function syncInspectorRendering(force=false){
      if(!inspection)return;
      const panel=$('inspect'),capable=!!(renderer?.gl&&!renderer.hadContextLoss&&options.backend!=='canvas'),hd=window.__NR_VISUAL,live=capable&&(!renderer.hdUI||hd?.presentation==='boss'&&hd.presentationKey==='boss-'+inspection.id&&hd.presentationFirstFrame!==false),pending=capable&&renderer.hdUI&&!window.__NR_VISUAL_LOAD_ERROR&&(!hd||hd.presentationState==='loading'),key=(live?'live':pending?'loading':'static')+language;
      if(!force&&panel.dataset.renderMode===key)return;
      panel.dataset.renderMode=key;
      panel.querySelector('[data-i18n="inspectModel"]').textContent=live?tx('inspectModel'):pending?coopText('CURRENT MODEL PREVIEW / LOADING 3D','当前模型预览 / 三维载入中'):coopText('STATIC PORTRAIT / CURRENT COMBAT MODEL','静态预览 / 当前战场模型');
      panel.querySelector('[data-i18n="inspectHint"]').textContent=live?tx('inspectHint'):pending?coopText('ROTATION & ZOOM AVAILABLE WHEN 3D IS READY','三维载入后可旋转与缩放'):coopText('STATIC PREVIEW / 3D CURRENTLY UNAVAILABLE','静态预览 / 三维暂不可用');
      $('inspectRotation').disabled=$('inspectAuto').disabled=!live;
      $('inspectAuto').textContent=live?coopText(inspection.auto?'AUTO ROTATE · ON':'AUTO ROTATE · OFF',inspection.auto?'自动旋转 · 开':'自动旋转 · 关'):coopText('STATIC PREVIEW','静态预览');
    }
    function refreshInspector(){if(!inspection||!$('inspectName'))return;const i=inspection.id,b=BOSSES[i],f=BOSS_FORM[i],l=language==='en'?0:2;$('inspectIndex').textContent='SOVEREIGN / '+String(i+1).padStart(2,'0')+' — 08';$('inspectName').textContent=b.name;$('inspectSub').textContent=b.sub;$('inspectForm').textContent=f[l];$('inspectDetail').textContent=f[l+1];$('inspectCombat').textContent=b.desc;$('inspectAuto').textContent=coopText(inspection.auto?'AUTO ROTATE · ON':'AUTO ROTATE · OFF',inspection.auto?'自动旋转 · 开':'自动旋转 · 关');$('inspectRotation').value=((inspection.yaw*180/Math.PI)%360+360)%360;$('inspect').style.setProperty('--boss',b.color);syncInspectorRendering(true);}
    function openInspector(id){if(!Number.isInteger(id)||id<0||id>7)return;if(state==='play')pauseGame();inspectionBack=state==='inspect'?inspectionBack:state;inspection={id,yaw:1.05,zoom:1,auto:true};hide('home');hide('select');hide('codexModal');hide('hud');hide('pauseModal');state='inspect';keys.clear();pointer.held=false;coopHUD();show('inspect');refreshInspector();}
    function closeInspector(){hide('inspect');inspection=null;if(inspectionBack==='select')openSelection();else if(inspectionBack==='paused'){state='paused';show('hud');show('pauseModal');coopHUD();}else{refreshHome();show('codexModal');}}
    function initInspector(){Object.assign(UI,{inspectReturn:['← ARCHIVE','← 返回图鉴'],inspectModel:['LIVE GEOMETRY / SAME MODEL IN COMBAT','实时几何 / 与战场相同的模型'],inspectHint:['DRAG TO ROTATE  /  SCROLL TO ZOOM','拖动旋转 / 滚轮缩放'],inspectMorph:['FORM & CONSTRUCTION','形态与结构'],inspectTactics:['COMBAT SIGNATURE','战斗特征'],inspectSelect:['PREVIOUS','上一位'],inspectNext:['NEXT SOVEREIGN →','下一位君主 →']});const s=document.createElement('section');s.id='inspect';s.className='screen hidden';s.innerHTML='<div class="inspect-vignette"></div><header class="inspect-top"><button id="inspectClose" class="quiet" data-i18n="inspectReturn"></button><span data-i18n="inspectModel"></span></header><div class="inspect-reticle"><i></i><i></i><span data-i18n="inspectHint"></span></div><aside class="inspect-panel"><span id="inspectIndex" class="eyebrow"></span><h1 id="inspectName"></h1><p id="inspectSub"></p><div class="inspect-rule"></div><small data-i18n="inspectMorph"></small><h3 id="inspectForm"></h3><p id="inspectDetail"></p><small data-i18n="inspectTactics"></small><p id="inspectCombat"></p><div class="inspect-controls"><input id="inspectRotation" type="range" min="0" max="360" value="24" aria-label="Rotate model"><button id="inspectAuto"></button></div><nav><button id="inspectPrevious" data-i18n="inspectSelect"></button><button id="inspectNext" data-i18n="inspectNext"></button></nav></aside>';$('app').append(s);$('inspectClose').onclick=closeInspector;$('inspectPrevious').onclick=()=>openInspector((inspection.id+7)%8);$('inspectNext').onclick=()=>openInspector((inspection.id+1)%8);$('inspectAuto').onclick=()=>{inspection.auto=!inspection.auto;refreshInspector();};$('inspectRotation').oninput=e=>{inspection.yaw=+e.target.value*Math.PI/180;inspection.auto=false;refreshInspector();};let drag=null;canvas.addEventListener('pointerdown',e=>{if(state==='inspect'&&$('inspect').dataset.renderMode==='live'+language){e.preventDefault();drag=e.clientX;canvas.setPointerCapture(e.pointerId);inspection.auto=false;refreshInspector();}});canvas.addEventListener('pointermove',e=>{if(state==='inspect'&&drag!==null){inspection.yaw+=(e.clientX-drag)*.008;drag=e.clientX;refreshInspector();}});window.addEventListener('pointerup',()=>drag=null);window.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{if(state==='inspect'&&$('inspect').dataset.renderMode==='live'+language){e.preventDefault();inspection.zoom=clamp(inspection.zoom-e.deltaY*.0006,.72,1.3);}},{passive:false});document.addEventListener('keydown',e=>{if(state==='inspect'&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeInspector();}},true);}
