    const OUI={tab:'squad',selected:'oathkeeper',draft:null,returnFocus:null,forgeBusy:false,hud:null};
    const O_LABELS={guard:['Guard','护卫'],rescue:['Rescue','救援'],retreat:['Retreat','撤退'],focus:['Focus boss','集火首领'],assault:['Assault','突击'],objective:['Objective','执行任务'],follow:['Follow','跟随'],always:['Always','总是'],never:['Never','不用'],ally_down:['An ally is down','队友倒地'],self_low:['Below 35% HP','自身生命低于 35%'],boss:['Boss present','首领在场'],ally_low:['Nearby ally below 60% HP','附近成员生命低于 60%'],danger:['Three nearby threats','近身威胁达到 3'],objective_threat:['Objective threatened','任务目标受威胁'],leader_assault:['Leader signals assault','队长下令突击'],leader_guard:['Leader signals guard','队长下令护卫'],distant:['Far from leader','距离队长过远'],boss_window:['Boss vulnerability window','首领进入破绽窗口'],moving:['Moving','正在移动'],boss_or_crowd:['Boss or crowd','首领或包围'],safe:['Not low on health','生命未处于危险'],balanced:['Adaptive','自适应'],vigor:['Vitality','生存'],swarm:['More blades','剑阵'],fury:['Attack','攻击'],none:['No memory','无记忆'],recovery:['Retreat until 70% HP','撤退记忆：恢复到 70% 才解除'],shield:['Shield','护盾'],heal:['Heal','治疗'],repulse:['Repulse','击退'],frost:['Freeze','冻结'],charge:['Charge','蓄能']};
    const ol=k=>O_LABELS[k]?.[language==='en'?0:1]||k;
    function oe(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
    function ob(text,fn,cls=''){const b=oe('button',cls,text);b.type='button';b.onclick=()=>{try{fn();}catch(e){oathError(e);}};return b;}
    function of(label,input){const l=oe('label','o-field');l.append(oe('span','',label),input);return l;}
    function os(options,value,change){const s=oe('select');for(const [v,label]of options)s.add(new Option(label,v,false,String(v)===String(value)));if(change)s.onchange=()=>{try{change(s.value);}catch(e){oathError(e);}};return s;}
    function oi(value,max=48){const i=oe('input');i.value=value||'';i.maxLength=max;return i;}
    function oathError(e){const messages={INCOMPATIBLE_CIRCUIT:['This chip uses a different game interface. Import an Oath ABI 1 circuit.','这个芯片的接口不兼容。请使用 Oath ABI 1 电路。'],WALLET_UNAVAILABLE:['Open this game in a browser with an injected wallet to manufacture. Free play and readback remain available.','制造需要支持钱包扩展的浏览器；仍可免费游玩和只读校验。'],QUOTE_CHANGED_REVIEW_AGAIN:['The price or selected version changed. Read a fresh quote.','价格或选择的版本发生变化，请重新读取报价。'],NOT_ENOUGH_RESEARCH:['Complete more encounters to earn research.','请完成更多遭遇来获得研究点。'],TRANSACTION_PENDING_DO_NOT_RESEND:['A previous transaction is pending. Check its receipt before retrying.','上一笔交易仍待确认。请先检查交易状态，再重试。'],REVIEW_QUOTE_FIRST:['Read the quote, then confirm the displayed cost.','请先读取报价，再确认显示的费用。']};const code=e.shortMessage||e.message||String(e),message=messages[code]?.[language==='en'?0:1]||code;const p=$('oathNotice');if(p){p.textContent=oathText('Could not complete: ','无法完成：')+message;p.classList.add('o-error');}else toast(message);}
    function oathNotice(text){$('oathNotice').textContent=text;$('oathNotice').classList.remove('o-error');}
    function oathActive(){return !!run&&!run.ended&&['play','paused','route','camp'].includes(state);}
    function oathOpen(tab='squad'){
      if(state==='play')pauseGame();OUI.returnFocus=document.activeElement;OUI.tab=tab;show('oathModal');oathRender();$('oathClose').focus();
    }
    function oathClose(){hide('oathModal');OUI.returnFocus?.focus?.();}
    function oathDownload(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=oe('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
    function oathUIInit(){
      Object.assign(UI,{oathWorkshop:['OATH WORKSHOP','誓约工坊'],oathContract:['Expedition contract','远征契约'],contract_none:['No contract','普通远征'],contract_scarcity:['Scarcity: energy −35%, research +30%','契约·匮乏：充能 −35%，研究 +30%'],contract_hunted:['Hunted: reinforcements +30%, research +30%','契约·追猎：增援 +30%，研究 +30%']});
      Object.assign(UI,{expedition:['OATH EXPEDITION','誓约远征'],expeditionNote:['Three regions · twelve encounters · routes, camps and circuit-built allies.','三个区域 · 十二场遭遇 · 分岔路线、营地与电路队友。'],partyDescription:['One leader: human or external AI. Three companions: tactical circuits or external AI.','一位队长：人类或外部 AI。三位队友：战术电路或外部 AI。'],partyTag:['FOUR MEMBERS. ONE OATH.','四位成员，同一个誓约。']});
      const modal=oe('div','modal hidden');modal.id='oathModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','oathTitle');
      const card=oe('div','modal-card oath-card'),top=oe('header','o-top');const titles=oe('div');titles.append(oe('div','eyebrow','NEON RELIQUARY / THE FOUNDRY'));const title=oe('h2');title.id='oathTitle';titles.append(title);
      const close=ob('×',oathClose,'modal-close');close.id='oathClose';close.setAttribute('aria-label',oathText('Close workshop','关闭工坊'));top.append(titles,close);card.append(top);
      const nav=oe('nav','o-tabs');nav.id='oathTabs';const notice=oe('p','o-notice');notice.id='oathNotice';notice.setAttribute('role','status');const body=oe('div','o-body');body.id='oathBody';card.append(nav,notice,body);modal.append(card);$('app').append(modal);
      for(const id of ['routeModal','campModal']){const e=oe('div','modal hidden');e.id=id;e.setAttribute('role','dialog');e.setAttribute('aria-modal','true');$('app').append(e);}
      const hud=oe('div','o-hud hidden');hud.id='oathHUD';$('app').append(hud);
      const home=ob(tx('oathWorkshop'),()=>oathOpen(),'o-workshop-button');home.id='oathHome';home.dataset.i18n='oathWorkshop';$('home').querySelector('.home-links').prepend(home);
      const button=ob('',()=>{mode='expedition';refreshSelection();});button.dataset.mode='expedition';button.dataset.i18n='expedition';document.querySelector('[data-mode]').parentElement.prepend(button);
      const controls=oe('div','o-contract'),contract=os(['none','scarcity','hunted'].map(v=>[v,tx('contract_'+v)]),'none');contract.id='oathContract';for(const option of contract.options)option.dataset.i18n='contract_'+option.value;const contractLabel=of(tx('oathContract'),contract);contractLabel.firstElementChild.dataset.i18n='oathContract';controls.append(contractLabel);$('select').querySelector('.selection-note').before(controls);
      document.addEventListener('keydown',e=>{
        if($('oathModal').classList.contains('hidden'))return;
        if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();oathClose();return;}
        if(e.key==='Tab'){const list=[...modal.querySelectorAll('button,input,select,textarea,a')].filter(x=>!x.disabled&&x.offsetParent!==null);if(!list.length)return;const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
      },true);
      mode='expedition';oathApplyLoadout();
    }
    function oathRender(){
      if(!$('oathTabs'))return;$('oathTitle').textContent=oathText('The Oath Workshop','誓约工坊');$('oathHome').textContent=oathText('OATH WORKSHOP','誓约工坊');
      const tabs=$('oathTabs');tabs.replaceChildren();for(const [id,en,zh]of [['squad','Squad','混编队伍'],['blueprint','Circuits & relics','芯片与圣物'],['lab','Circuit lab','电路试验'],['forge','TapeOut / X Layer','流片与链上读回']]){const b=ob(oathText(en,zh),()=>{OUI.tab=id;oathRender();},OUI.tab===id?'chosen':'');b.setAttribute('aria-current',OUI.tab===id?'page':'false');tabs.append(b);}
      $('oathBody').replaceChildren();oathNotice(OATH.warning?oathText('The saved profile could not be read. Export a backup before resetting. Changes stay in memory.','存档读取失败。请先备份再重置；当前更改仅留在内存。'):oathText('Free blueprints play immediately. Manufacturing creates a fixed on-chain version.','免费蓝图可以直接游玩。流片制造的是逻辑固定的链上版本。'));
      if(OATH.warning){const bar=oe('div','o-actions');bar.append(ob(oathText('Export damaged save','导出原存档'),()=>oathDownload('oath-save-backup.txt',localStorage.getItem(OD.KEY)||'')),ob(oathText('Reset this profile','重置此存档'),()=>{OATH.warning=null;oathSave();oathRender();}));$('oathBody').append(bar);}
      ({squad:oathSquad,blueprint:oathBlueprint,lab:oathLab,forge:oathForge})[OUI.tab]();
    }
    function oathOptions(kind,empty=false){const opts=OD.list(OATH.profile).filter(r=>OC.decode(r.circuit).kind===kind).map(r=>[r.id,oathName(r)+(r.source.type==='xlayer'?oathText(' · chain',' · 链上'):'')]);if(empty)opts.unshift(['',oathText('Empty socket','空槽')]);return opts;}
    function oathSquad(){
      const body=$('oathBody'),p=OATH.profile,l=p.loadout,locked=oathActive();
      body.append(oe('p','o-intro',oathText('Choose your companions and two relics per member. Chips make decisions; external AI takes its own reserved seat. Changes lock when an expedition begins.','为每位成员选择控制来源与两件圣物。芯片自行决策，外部 AI 进入预留席位。远征开始后锁定配装。')));
      const grid=oe('div','o-squad-grid');
      for(let seat=0;seat<4;seat++){
        const config=seat?l.slots[seat-1]:null,c=oe('section','o-unit-card'),h=oe('h3','',seat?oathText('Companion ','队友 ')+seat:oathText('Leader · your selected class','队长 · 当前选择的职业'));c.append(h);
        const connection=seat?PARTY.slots[seat-1]:OATH.leader,controller=seat?config.mode:l.leader;
        const status=connection.token?oathText('Connected: ','已连接：')+connection.name+(connection.pending?oathText(' · next encounter',' · 下一遭遇部署'):''):controller==='external'?oathText('Waiting for AI','等待 AI 加入'):controller==='chip'?oathText('Circuit controlled','电路控制'):controller==='human'?oathText('Human controlled','人类控制'):oathText('Seat closed','席位关闭');
        c.append(oe('p','o-small o-unit-status',status));
        const modeOptions=seat?[['chip',oathText('Tactical chip','战术芯片')],['external',oathText('External AI','外部 AI')],['off',oathText('Closed','关闭')]]:[['human',oathText('Human control','人类控制')],['external',oathText('External AI','外部 AI')]];
        c.append(of(oathText('Controller','控制来源'),os(modeOptions,seat?config.mode:l.leader,v=>{if(seat)config.mode=v;else l.leader=v;oathApplyLoadout();oathSave();oathRender();})));
        if(seat)c.append(of(oathText('Class','职业'),os(HEROES.map((h,i)=>[i,h.name]),config.heroId,v=>{config.heroId=+v;oathApplyLoadout();oathSave();})));
        if(seat&&config.mode==='chip')c.append(of(oathText('Decision circuit','战术电路'),os(oathOptions('tactic'),config.chip,v=>{config.chip=v;oathApplyLoadout();oathSave();})));
        if((seat?config.mode:l.leader)==='external')c.append(oe('p','o-small',oathText('Reserve seat '+seat+'. Join with nr_join, then send intentions through nr_command.','预留席位 '+seat+'。用 nr_join 加入，再通过 nr_command 下达意图。')));
        const rs=seat?config.relics:l.leaderRelics,relics=oe('div','o-unit-relics');
        for(let j=0;j<2;j++)relics.append(of(oathText('Relic ','圣物 ')+(j+1),os(oathOptions('relic',true),rs[j],v=>{rs[j]=v||null;oathApplyLoadout();oathSave();})));
        c.append(relics);
        if(locked)for(const input of c.querySelectorAll('select'))input.disabled=true;grid.append(c);
      }
      body.append(grid);
      const bar=oe('div','o-actions');const name=oi('',40);name.placeholder=oathText('Name this squad','队伍方案名称');bar.append(name,ob(oathText('Save squad','保存队伍'),()=>{const n=name.value.trim();if(!n)throw Error(oathText('Enter a squad name','请输入队伍名'));const old=p.squads.find(s=>s.name===n);if(old)old.loadout=OD.clone(l);else{if(p.squads.length>=12)throw Error('SQUAD_LIMIT');p.squads.push({name:n,loadout:OD.clone(l)});}oathSave();oathRender();}));
      const saved=os([['',oathText('Saved squads','已存队伍')],...p.squads.map((s,i)=>[i,s.name])],'',v=>{if(v==='')return;p.loadout=OD.validateLoadout(p.squads[+v].loadout,p);oathApplyLoadout();oathSave();oathRender();});saved.disabled=locked;bar.append(saved);body.append(bar);
      if(locked)body.append(oe('p','o-small',oathText('Loadout locked for this run. Return to selection to equip changes.','本局配装已锁定。回到选择界面后可更换。')));
      if(P?.controller==='external')body.append(ob(oathText('Take over the leader now','立即接管队长'),()=>{oathTakeover();oathRender();},'primary'));
      const consent=ob(PARTY.enabled?oathText('Revoke all external access','撤销全部外部控制'):oathText('Enable reserved external seats','开启预留外部席位'),()=>{PARTY.enabled=!PARTY.enabled;if(!PARTY.enabled){oathTakeover();for(const s of PARTY.slots)if(s.mode==='external')coopRelease(s,'host_revoked');}oathRender();});body.append(consent);
      body.append(oe('h3','',oathText('Research archive · ','研究档案 · ')+p.research));
      const unlocks=oe('div','o-unlocks');for(const [effect,b]of Object.entries(OD.bases)){const unlocked=p.unlocked.includes(effect),button=ob(b[language]+(unlocked?' ✓':' · '+OD.effectCosts[effect]),()=>{if(locked)throw Error('LOADOUT_LOCKED');OD.unlock(p,effect);oathSave();oathRender();});button.disabled=unlocked||locked||p.research<OD.effectCosts[effect];button.title=b.description[language==='en'?0:1];unlocks.append(button);}body.append(unlocks,oe('p','o-small',oathText('Every cleared encounter earns research. Unlocks add options; they do not multiply damage. Each member shares 100 energy across both relics, regenerating 2.2/s.','每次完成遭遇可获得研究点。解锁增加选择，每位成员的两件圣物共享 100 能量，每秒恢复 2.2。')));
      if(p.history.length)body.append(oe('p','o-small',oathText('Expeditions ','远征 ')+p.runs+' · '+oathText('Victories ','胜利 ')+p.wins+' · '+oathText('Latest research +','最近获得研究 +')+p.history[0].research));
    }
    function oathBlueprint(){
      const body=$('oathBody'),record=OD.find(OATH.profile,OUI.selected)||OD.list(OATH.profile)[0];OUI.selected=record.id;
      body.append(of(oathText('Library · select a template to create a new version','蓝图库 · 选择模板，制作新版本'),os(OD.list(OATH.profile).map(r=>[r.id,oathName(r)]),record.id,v=>{OUI.selected=v;OUI.draft=null;oathRender();})));
      body.append(oe('p','o-small',(record.source.type==='xlayer'?oathText(OATH.verified.has(record.id)?'Verified this session':'Chain claim · re-read required',OATH.verified.has(record.id)?'本会话已校验':'链上来源声明 · 尚需重新读回'):record.preset?oathText('Included template','内置模板'):oathText('Local draft version','本地草稿版本'))+(record.parent?' · '+oathText('Parent: ','父版本：')+record.parent:'')));
      const b=record.blueprint?OD.clone(OUI.draft||record.blueprint):null;
      const editor=oe('div','o-editor'),preview=oe('pre','o-netlist');preview.id='oathCompileResult';
      const compile=()=>{if(b){OUI.draft=OD.clone(b);const c=OC.compile(b);preview.textContent=oathText('Compiled successfully','编译通过')+' · '+c.nNand+' NAND + '+c.nLatch+' LATCH · '+c.bytes+' bytes\n'+oathText('ABI 1 · 20 inputs · ','ABI 1 · 20 输入 · ')+c.nOut+oathText(' outputs',' 输出');return c;}return OC.decode(record.circuit);};
      if(b){
        const name=oi(b.name);name.oninput=()=>{b.name=name.value;try{compile();}catch(e){preview.textContent=e.message;}};editor.append(of(oathText('Version name','版本名称'),name));
        if(b.kind==='tactic'){
          editor.append(oe('p','o-small',oathText('Top match wins. Unmatched states guard. Movement and collisions still follow the game rules.','从上到下匹配，第一条命中生效；未命中时护卫。移动与碰撞仍遵循游戏规则。')));
          const rules=oe('div','o-rules');b.rules.forEach((r,i)=>{const row=oe('div','o-rule');row.append(oe('b','',String(i+1)),of(oathText('When','条件'),os(OC.CONDITIONS.map(k=>[k,ol(k)]),r.when,v=>{r.when=v;compile();})),of(oathText('Then','行动'),os(OC.ACTIONS.map(k=>[k,ol(k)]),r.action,v=>{r.action=v;compile();})),ob('↑',()=>{if(i>0){[b.rules[i-1],b.rules[i]]=[b.rules[i],b.rules[i-1]];OUI.draft=b;oathRender();}}),ob('−',()=>{if(b.rules.length>1){b.rules.splice(i,1);OUI.draft=b;oathRender();}}));rules.append(row);});editor.append(rules);
          if(b.rules.length<6)editor.append(ob(oathText('Add rule','添加规则'),()=>{b.rules.push({when:'always',action:'guard'});OUI.draft=b;oathRender();}));
          const skills=oe('div','o-three');for(const [k,en,zh]of [['skill','Skill request','技能请求'],['ultimate','Ultimate request','终极技请求'],['dash','Dash request','闪避请求']])skills.append(of(oathText(en,zh),os(['never',...OC.CONDITIONS].map(k=>[k,ol(k)]),b.skills[k],v=>{b.skills[k]=v;compile();})));editor.append(skills);
          editor.append(of(oathText('Upgrade direction','升级方向'),os(['balanced','vigor','swarm','fury'].map(k=>[k,ol(k)]),b.upgrade,v=>{b.upgrade=v;compile();})),of(oathText('Memory','记忆'),os(['none','recovery'].map(k=>[k,ol(k)]),b.memory,v=>{b.memory=v;compile();})));
        }else{
          editor.append(of(oathText('Relic chassis','圣物底座'),os(OC.EFFECTS.map(k=>[k,OD.bases[k][language]+(OATH.profile.unlocked.includes(k)?'':oathText(' · locked',' · 待解锁'))]),b.effect,v=>{b.effect=v;compile();})),of(oathText('Trigger','触发条件'),os(OC.CONDITIONS.map(k=>[k,ol(k)]),b.trigger,v=>{b.trigger=v;compile();})),of(oathText('Memory','记忆'),os([['none',ol('none')],['rescue',oathText('Arm on rescue; consume after a successful effect','救援后储存，效果成功后消耗')]],b.memory,v=>{b.memory=v;compile();})));
        }
        const note=oi('',200);editor.append(of(oathText('What changed?','改了什么？'),note));editor.append(ob(oathText('Save as a new version','保存为新版本'),()=>{compile();const r=OD.add(OATH.profile,b,{parent:record.id,note:note.value});OUI.selected=r.id;OUI.draft=null;oathSave();oathRender();oathNotice(oathText('Saved. Equip it from the Squad tab.','已保存。请在混编队伍页装备。'));},'primary'));
      }else editor.append(oe('p','',oathText('This circuit was read from chain. Its netlist is immutable; import a source blueprint to edit a new version.','这是链上读回的固定网表。若要编辑新版本，请导入原始蓝图。')));
      body.append(editor,preview);compile();const actions=oe('div','o-actions');actions.append(ob(oathText('Export BLIF','导出 BLIF'),()=>oathDownload('oath-'+record.id+'.blif',OC.exportBLIF(compile()))),ob(oathText('Export netlist','导出网表'),()=>{const c=compile();oathDownload('oath-'+record.id+'.json',JSON.stringify({netlist:c.netlist,nIn:c.nIn,nOut:c.nOut},null,2),'application/json');}),ob(oathText('Share saved version','分享已存版本'),()=>oathDownload(record.id+'.oath.json',OD.share(OATH.profile,record.id),'application/json')));body.append(actions);
      const input=oe('textarea');input.rows=4;input.maxLength=150000;input.placeholder=oathText('Paste a shared blueprint package','粘贴分享的蓝图包');input.setAttribute('aria-label',input.placeholder);body.append(input,ob(oathText('Import shared blueprint','导入分享蓝图'),()=>{const r=OD.importShare(OATH.profile,input.value);OUI.selected=r.id;OUI.draft=null;oathSave();oathRender();}));
      const file=oe('input');file.type='file';file.accept='.json';file.setAttribute('aria-label',oathText('Import blueprint file','导入蓝图文件'));file.onchange=async()=>{try{const f=file.files[0];if(!f||f.size>150000)throw Error('PACKAGE_TOO_LARGE');const r=OD.importShare(OATH.profile,await f.text());OUI.selected=r.id;OUI.draft=null;oathSave();oathRender();}catch(e){oathError(e);}};body.append(file);
    }
    function oathLab(){
      const body=$('oathBody');body.append(oe('p','o-intro',oathText('Compare actual circuit outputs against an included template. Fixed input traces test decisions and memory. This is a logic bench, not a combat win-rate claim.','把电路实际输出与内置模板比较。固定输入序列检查决策与记忆；这里是逻辑试验台，结果不代表整局胜率。')));
      const options=OD.list(OATH.profile).map(r=>[r.id,oathName(r)]),chosen=os(options,OUI.selected),base=os(options,'oathkeeper');body.append(of(oathText('Candidate','候选版本'),chosen),of(oathText('Baseline','对照版本'),base));
      const out=oe('div','o-table-scroll');out.tabIndex=0;out.setAttribute('aria-label',oathText('Circuit comparison results','电路对比结果'));body.append(ob(oathText('Run five scenarios','运行五组场景'),()=>{
        out.replaceChildren();const table=oe('table','o-table'),head=oe('tr');for(const t of [oathText('Scenario','场景'),oathText('Candidate output','候选输出'),oathText('Baseline output','对照输出')])head.append(oe('th','',t));table.append(head);
        const traces=[['Rescue under pressure','压力救援',[{ally_down:true,danger:true},{ally_down:true},{rescue_event:true}]],['Recovery memory','恢复记忆',[{self_low:true},{},{self_recovered:true}]],['Objective defense','守卫任务',[{objective:true},{objective:true,objective_threat:true,danger:true}]],['Boss opening','首领破绽',[{boss:true},{boss:true,boss_window:true,ultimate_ready:true}]],['Stored rescue / acknowledgement','救援储存与回执',[{rescue_event:true},{ally_low:true},{ally_low:true,effect_applied:true},{ally_low:true}]]];
        for(const [en,zh,trace]of traces){const row=oe('tr');row.append(oe('th','',oathText(en,zh)));for(const id of [chosen.value,base.value]){const c=OC.decode(OD.find(OATH.profile,id).circuit);let s=new Uint8Array(c.nState);const outputs=[];for(const f of trace){const r=OC.step(c,s,OC.bits({alive:true,relic_ready:true,skill_ready:true,blade_room:true,...f}));s=r.state;const d=OC.interpret(c,r.outputs);outputs.push(c.kind==='tactic'?ol(d.tactic)+(d.skill?' + E':'')+(d.ultimate?' + R':'')+' / '+d.upgradePath:ol(d.effect||'—'));}row.append(oe('td','',outputs.join(' → ')));}table.append(row);}out.append(table,oe('p','o-small',oathText('Upgrade output: 0 attack, 1 blades, 2 vitality. Each arrow is one logical tick; successful effects send acknowledgement on the next tick.','升级输出：0 攻击、1 剑阵、2 生存。每个箭头代表一次逻辑步；效果成功后在下一步返回回执。')));
      },'primary'),out);
    }
    function expeditionRenderRoute(){
      const ex=run.expedition,root=$('routeModal');root.replaceChildren();const c=oe('div','modal-card o-route-card');c.append(oe('div','eyebrow',oathText('THE LAST LIGHT / CHAPTER ','最后之光 / 区域 ')+(ex.chapter+1)+' · '+(ex.node+1)+'/4'),oe('h2','',oathText('Choose the next passage','选择下一段路')),oe('p','',oathText('All members carry their health, upgrades and relic memory forward.','所有成员保留当前生命、升级与圣物记忆继续前进。')));
      const map=oe('div','o-route-map');for(let i=0;i<12;i++)map.append(oe('span',i<ex.cleared?'done':i===ex.cleared?'current':'',i%4===3?'♛':String(i%4+1)));c.append(map);
      const grid=oe('div','o-route-options');for(const t of expeditionOptions()){const b=ob('',()=>expeditionChoose(t),'o-route-option');b.append(oe('strong','',EX_TYPES[t][language]),oe('span','',EX_TYPES[t].tip[language==='en'?0:1]),oe('small','',oathText('Research +','研究 +')+(t==='boss'?15:5)+' · '+oathText('Limit ','时限 ')+EX_TYPES[t].seconds+'s'));grid.append(b);}c.append(grid,ob(oathText('Inspect squad','查看队伍'),()=>oathOpen('squad')),ob(oathText('Abandon expedition','放弃本次远征'),()=>finish(false),'quiet'));root.append(c);
    }
    function expeditionRenderCamp(){const root=$('campModal');root.replaceChildren();const c=oe('div','modal-card o-route-card');c.append(oe('div','eyebrow',oathText('CAMP / PASSAGE SECURED','营地 / 路线已打通')),oe('h2','',oathText('One gift for the whole squad','为全队选择一份补给')),oe('p','',oathText('Downed allies return at camp. Your choice is consumed once, then the route continues.','倒地成员将在营地复苏。补给仅选择一次，之后继续远征。')));const grid=oe('div','o-route-options');for(const [id,en,zh,tipEn,tipZh]of [['mend','Mending oath','修复誓约','Heal 45% and +6 max HP','恢复 45% 生命，上限 +6'],['edge','Honed steel','磨砺兵刃','Damage +7% this expedition','本次远征伤害 +7%'],['battery','Shared embers','余烬补给','Restore 40 relic energy','圣物能量恢复 40']]){const b=ob('',()=>expeditionReward(id),'o-route-option');b.append(oe('strong','',oathText(en,zh)),oe('span','',oathText(tipEn,tipZh)));grid.append(b);}c.append(grid);root.append(c);}
    function oathHUD(){
      const h=$('oathHUD');if(!h)return;h.classList.toggle('hidden',!run||!['play','paused'].includes(state));if(!run||!P)return;for(const id of ['dashBtn','skillBtn','ultBtn'])$(id).disabled=P.controller==='external';
      // Keep interactive nodes stable: a 10 Hz refresh must not cancel pointer clicks or keyboard focus.
      if(!OUI.hud){const title=oe('div','o-objective-title'),detail=oe('div','o-small'),bar=oe('div','o-command-bar'),energy=oe('span'),takeover=ob('',oathTakeover),commands={};for(const cmd of ['guard','assault']){commands[cmd]=ob('',()=>{OATH.command=cmd;});bar.append(commands[cmd]);}bar.append(energy,takeover);h.append(title,detail,bar);OUI.hud={title,detail,energy,takeover,commands};}
      const ui=OUI.hud,ex=run.expedition;ui.title.classList.toggle('hidden',!ex);ui.detail.classList.toggle('hidden',!ex?.objective);
      if(ex){const ob=ex.objective;let status=oathText('Chapter ','区域 ')+(ex.chapter+1)+' / '+(ex.node+1)+' · '+EX_TYPES[ex.type]?.[language];if(ob)status+=' · '+Math.floor(ob.progress/ob.target*100)+'% · '+oathText('Integrity ','完整度 ')+Math.ceil(ob.hp);else if(ex.type==='clear')status+=' · '+Math.min(200,run.kills-ex.startKills)+'/200';else if(ex.type==='boss')status+=' · '+oathText(ex.bossWindow?'BURST NOW':'Opening in ',ex.bossWindow?'破绽：爆发！':'破绽倒计时 ')+(ex.bossWindow?'':Math.ceil(17-ex.clock%24)+'s');ui.title.textContent=status;if(ob)ui.detail.textContent=oathText('Objective ','目标 ')+Math.round(ob.x-P.x)+', '+Math.round(ob.y-P.y)+' · '+oathText('relative to you','相对你的位置');}
      for(const cmd of ['guard','assault']){ui.commands[cmd].textContent=ol(cmd);ui.commands[cmd].classList.toggle('chosen',OATH.command===cmd);}
      ui.energy.textContent=oathText('Relic energy ','圣物能量 ')+Math.floor(P.oath?.energy||0);ui.takeover.classList.toggle('hidden',P.controller!=='external');ui.takeover.textContent=oathText(P.stale?'AI waiting · take over':'AI leader · take over',P.stale?'AI 等待中 · 接管':'AI 队长 · 接管');
    }

    function oathResult(){
      const ex=run?.expedition;if(!ex)return;
      const reason=ex.failure==='objective_lost'?oathText('The objective was lost.','任务目标失守。'):ex.failure==='timeout'?oathText('The encounter time limit expired.','遭遇时间已耗尽。'):'';
      $('resultDesc').textContent=reason+oathText('Passages cleared ','已完成遭遇 ')+ex.cleared+'/12 · '+oathText('Research +','研究 +')+(ex.reward||0);
      $('resultStats').replaceChildren();for(const [label,value]of [[oathText('Passages','遭遇'),ex.cleared+'/12'],[oathText('Bosses','首领'),run.bosses+'/3'],[oathText('Time','时间'),formatTime(run.time)],[oathText('Rescues','救援'),run.coopRescues||0],[oathText('Research','研究'),ex.reward||0]]){const d=oe('div');d.append(oe('strong','',String(value)),oe('small','',label));$('resultStats').append(d);}
    }
